"use client";
import Link from "next/link";
import { m } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Bot, Cable, CircleOff, Droplets, Layers3, Users } from "@/components/ui/animated-icons";

const faqs = [
  ["What is the biggest challenge businesses face today?", "The biggest challenge is not access to technology. It is the inability to connect systems, customer information, and workflows into one intelligent operating foundation."],
  ["Why are disconnected systems a problem?", "Information fragments across tools, teams lose visibility into the full journey, customers experience inconsistent communication, and opportunities disappear without anyone knowing why."],
  ["Why is more software not always better?", "A new tool without a connection plan usually adds complexity faster than value. Advantage comes from connecting what already exists."],
  ["What is business fragmentation?", "It is the state of customer and operational data being spread across disconnected systems, each holding a partial view and none sharing a complete picture."],
  ["How does AI change business operations?", "AI can understand behavior, prioritize opportunities, and act quickly, but only when connected to accurate, complete information."],
  ["What is Operating Intelligence?", "Operating Intelligence connects data, customer interactions, systems, workflows, and AI capabilities so a business can decide better, operate efficiently, and continuously improve growth."],
];
function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) { return <m.div initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .14 }} transition={{ delay, duration: .7, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</m.div>; }
function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) { return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className="flux-kicker text-flux">{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.6rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>; }
function FragmentationVisual() { return <div className="relative min-h-[430px] overflow-hidden rounded-[2rem] bg-ink p-7 text-white"><m.div animate={{ rotate: 360 }} transition={{ duration: 35, repeat: Infinity, ease: "linear" }} className="absolute -right-24 -top-24 h-80 w-80 rounded-[42%_58%_62%_38%] border border-white/15" /><div className="relative z-10 grid min-h-[376px] grid-cols-2 gap-4">{["Website", "CRM", "Marketing", "Automation", "Analytics", "AI"].map((item, index) => <m.div key={item} animate={{ x: index % 2 ? [0, 8, 0] : [0, -8, 0], y: [0, index % 3 ? -6 : 6, 0] }} transition={{ duration: 4 + index * .4, repeat: Infinity }} className="flex items-center justify-center rounded-2xl border border-white/15 bg-white/10 text-sm backdrop-blur">{item}</m.div>)}</div><span className="absolute left-1/2 top-1/2 z-20 flex h-16 w-16 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-flux"><CircleOff /></span></div>; }

export default function TheProblemPage() {
  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><m.div animate={{ x: [0, 65, -30, 0], y: [0, -40, 35, 0], borderRadius: ["38% 62% 56% 44%", "65% 35% 43% 57%", "44% 56% 66% 34%", "38% 62% 56% 44%"] }} transition={{ duration: 20, repeat: Infinity }} className="pointer-events-none absolute -right-32 top-24 h-[31rem] w-[31rem] bg-pulse opacity-40 blur-2xl" /><div className="flux-shell relative z-10"><nav className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/philosophy">Why Flux</Link><span className="mx-2">/</span><span>The Problem</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.2fr_.8fr] lg:items-end lg:py-16"><m.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }}><p className="flux-kicker mb-7 text-flux">The Problem</p><h1 className="font-display text-[clamp(3.25rem,5.8vw,6.2rem)] font-medium leading-[.91] tracking-[-.07em]">Businesses do not have a technology problem. <span className="text-flux">They have a connection problem.</span></h1></m.div><m.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Businesses use more technology than ever. Growth still feels harder because systems, data, and customer experiences do not share what they know—and opportunities quietly disappear between them.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/operating-intelligence" className="flux-button flux-button-red">Discover Operating Intelligence <ArrowUpRight size={16} /></Link><Link href="/business-intelligence-audit" className="flux-button flux-button-line">Measure your score</Link></div></m.div></div><a href="#changed" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">See the problem <ArrowDownRight size={16} /></a></div></section>

    <section id="changed" className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="The business world changed">Most companies are still competing in the previous era.</Heading><div className="mt-14 grid gap-4 md:grid-cols-3">{[["Era One", "Physical", "Location created advantage. Being where customers already were was most of the game."], ["Era Two", "Digital", "Websites, advertising, and search visibility shifted advantage to the strongest online footprint."], ["Era Three", "Intelligent", "Advantage now comes from connecting systems, understanding customers, and responding faster."]].map(([era, title, body], index) => <Reveal key={era} delay={index * .07} className={`flex min-h-[340px] flex-col justify-between rounded-[2rem] p-8 ${index === 2 ? "bg-flux text-white" : index === 1 ? "bg-pulse-light" : "bg-cream"}`}><span className="flux-kicker opacity-45">{era}</span><div><h3 className="font-display text-4xl font-medium">{title}</h3><p className="mt-6 text-sm leading-7 opacity-65">{body}</p></div></Reveal>)}</div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="More tools, more complexity">Each tool works. None work together.</Heading><div className="mt-14 grid gap-10 lg:grid-cols-[.55fr_.45fr]"><Reveal className="space-y-7 text-xl leading-9 text-ink/65"><p>The modern stack runs Website → CRM → Email → Phone → Analytics → Automation → AI → Customers. Every part was added for a valid reason.</p><p>The CRM cannot see what a customer read. Automation lacks context from other channels. Analytics counts traffic without connecting it to long-term relationships.</p><p>As tools accumulate without a connection plan, complexity compounds until nobody can confidently say where growth comes from or where it disappears.</p></Reveal><FragmentationVisual /></div></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="The fragmentation problem" light>A partial view mistaken for a complete one.</Heading><div className="mt-14 grid gap-4 md:grid-cols-3">{[["Marketing", "Sees traffic and leads but often cannot see which became paying customers.", Layers3], ["Customers", "Experience slow responses, repeated questions, and disjointed communication.", Users], ["Ownership", "Must decide what to fix using instinct because evidence is scattered across conflicting logins.", Cable]].map(([title, body, Icon], index) => { const ProblemIcon = Icon; return <Reveal key={title as string} delay={index * .07} className={`flex min-h-[340px] flex-col justify-between rounded-[2rem] p-8 ${index === 1 ? "bg-flux" : "border border-white/20"}`}><ProblemIcon /><div><h3 className="font-display text-3xl font-medium">{title as string}</h3><p className="mt-5 text-sm leading-7 opacity-60">{body as string}</p></div></Reveal>; })}</div></div></section>

    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="The hidden revenue leak">Opportunity rarely disappears dramatically. It leaks through invisible gaps.</Heading><div className="mt-14 grid gap-5 lg:grid-cols-[.4fr_.6fr]"><Reveal className="flex min-h-[390px] flex-col justify-between rounded-[2rem] bg-flux p-8 text-white"><Droplets size={34} /><p className="font-display text-4xl font-medium">A missed enquiry.<br />An unread form.<br />An unowned follow-up.<br />A broken handoff.</p></Reveal><Reveal delay={.08} className="space-y-7 rounded-[2rem] bg-cream p-8 text-xl leading-9 text-ink/65 md:p-12"><p>These losses never appear as a marketing failure. They appear as a quieter month and get blamed on weak demand.</p><p>Often the demand was present. The systems handling it after arrival were not connected enough to capture it.</p><p>Each gap looks small. Across a year, they become a meaningful revenue leak nobody can see on one dashboard.</p></Reveal></div></div></section>

    <section className="bg-flux py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Why old growth approaches break" light>Spending more to fill a leaking system makes the leak more expensive.</Heading><div className="mt-14 grid gap-5 lg:grid-cols-2"><Reveal className="rounded-[2rem] border border-white/25 p-8 md:p-12"><p className="flux-kicker text-white/45">Old approach</p><p className="mt-12 font-display text-5xl font-medium">More ads.<br />More traffic.<br />More tools.</p><p className="mt-8 text-white/60">Hope enough volume compensates for whatever disappears downstream.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-white p-8 text-ink md:p-12"><p className="flux-kicker text-flux">New reality</p><p className="mt-12 font-display text-5xl font-medium">Connected intelligence.</p><p className="mt-8 text-ink/60">See precisely where current opportunities are lost and fix the gap before paying to feed it more demand.</p></Reveal></div></div></section>

    <section className="bg-cream py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="The AI era changed the rules">AI raises the cost of fragmented information.</Heading><div className="mt-14 grid gap-10 lg:grid-cols-[.62fr_.38fr]"><Reveal className="space-y-7 text-xl leading-9 text-ink/65"><p>Missed-call AI needs to know what the caller asked. Lead prioritization needs accurate connected customer data. Neither works when information lives in systems that cannot share it.</p><p>AI does not remove the need for connection. Layered on fragmented data, it produces faster, more confident-sounding decisions built on the same incomplete picture.</p></Reveal><Reveal delay={.08} className="flex min-h-[340px] flex-col justify-between rounded-[2rem] bg-ink p-8 text-white"><Bot size={34} className="text-flux" /><p className="font-display text-4xl font-medium">Incomplete context creates faster incomplete decisions.</p></Reveal></div></div></section>

    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="The missing layer">Operating Intelligence connects what is already there.</Heading><div className="mt-14 grid gap-8 lg:grid-cols-[.6fr_.4fr]"><Reveal className="text-xl leading-9 text-ink/65"><p>Operating Intelligence connects customer information, systems, automation, and AI into one foundation—revealing where opportunities are won or lost and enabling action.</p><p className="mt-7">Flux builds the connective structure that makes the existing stack function as one system, not another piece of software.</p></Reveal><Link href="/operating-intelligence" className="group flex min-h-[260px] flex-col justify-between rounded-[2rem] bg-flux p-8 text-white transition-transform duration-500 hover:-translate-y-2"><ArrowUpRight className="ml-auto" /><p className="font-display text-3xl font-medium">Discover Operating Intelligence</p></Link></div></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="The Flux solution" light>Five connected systems address five parts of fragmentation.</Heading><div className="mt-14 grid border-t border-white/20 md:grid-cols-2 lg:grid-cols-5">{[["Operating Intelligence", "/operating-intelligence"], ["Revenue Intelligence", "/revenue-intelligence"], ["Customer Progression", "/customer-progression"], ["AI Discovery", "/ai-discovery"], ["Patient Revenue System", "/patient-revenue-system"]].map(([title, href]) => <Link key={title} href={href} className="group flex min-h-[240px] flex-col justify-between border-b border-white/20 p-7 transition-colors hover:bg-white hover:text-ink md:border-r"><ArrowUpRight className="ml-auto" /><h3 className="font-display text-2xl font-medium">{title}</h3></Link>)}</div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Who faces this problem">Fragmentation appears anywhere customers cross multiple channels.</Heading><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{[["Healthcare", "/industries/healthcare"], ["Home services", "/industries/home-services"], ["Legal", "/industries/legal"], ["Wellness", "/industries/wellness"], ["Professional services", "/solutions"]].map(([title, href], index) => <Reveal key={title} delay={index * .05}><Link href={href} className="flex min-h-[210px] flex-col justify-between rounded-[1.75rem] bg-white p-7 transition-transform hover:-translate-y-2"><span className="text-xs font-bold text-flux">0{index + 1}</span><h3 className="font-display text-2xl font-medium">{title}</h3></Link></Reveal>)}</div></div></section>

    <section className="bg-cream py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="FAQ">Questions about disconnected business systems.</Heading><div className="mt-14 divide-y divide-ink/15 border-y border-ink/15">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 items-center justify-center rounded-full border border-ink/15 transition-transform group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>

    <section className="bg-flux py-24 text-white md:py-36"><div className="flux-shell"><p className="flux-kicker text-white/55">Close the connection gap</p><Reveal><h2 className="mt-7 max-w-6xl font-display text-[clamp(3rem,5.5vw,5.7rem)] font-medium leading-[.95] tracking-[-.06em]">Discover Operating Intelligence—or measure where your own business stands.</h2></Reveal><div className="mt-10 flex flex-wrap gap-4"><Link href="/operating-intelligence" className="flux-button bg-white text-ink">Explore the solution <ArrowUpRight size={16} /></Link><Link href="/business-intelligence-audit" className="flux-button border border-white/30 text-white">Measure your score</Link><Link href="/philosophy" className="flux-button border border-white/30 text-white">Read our philosophy</Link></div></div></section>
  </>;
}
