"use client";
import Link from "next/link";
import { FormEvent, useMemo, useRef, useState } from "react";
import { m } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Check, Loader2, RotateCcw } from "@/components/ui/animated-icons";

const ACCESS_KEY = "9c81aa58-8835-4d78-87db-6a707c241ba9";
const areas = [
  ["01", "Discovery Intelligence", "Can customers find you?", "Visibility across traditional search, AI tools, and a digital presence that clearly explains what you do and whom you serve."],
  ["02", "Customer Journey Intelligence", "What happens after someone finds you?", "Website conversion, response speed, consistency, and friction between interest and the next action."],
  ["03", "Revenue Intelligence", "Where are opportunities being lost?", "Lead tracking, follow-up consistency, and visibility into where prospects drop between contact and conversion."],
  ["04", "Operational Intelligence", "How connected are your systems?", "Whether your website, CRM, communications, and workflows share useful information or operate as islands."],
  ["05", "AI Readiness", "Can your business compete in the AI era?", "How clearly AI search and recommendation systems can understand, trust, and recommend your business."],
];
const faqItems = [
  ["What is a Business Intelligence Audit?", "A Business Intelligence Audit evaluates how effectively a company discovers customers, manages the customer journey, converts opportunities, and uses its systems to support growth, producing a scored view of where revenue is being lost."],
  ["How long does the audit take?", "Most businesses complete the assessment in under ten minutes. Your initial score and findings appear immediately."],
  ["What does the Business Intelligence Score measure?", "It measures discovery, customer journey, revenue, operations, and AI readiness."],
  ["Is this only for healthcare businesses?", "No. It applies to service businesses including healthcare, home services, legal, wellness, and professional services."],
  ["How can businesses improve their AI readiness?", "By making structured data, published content, reviews, and business information clear and consistent enough for AI systems to understand and recommend them."],
  ["What happens after completing the audit?", "You receive an estimated score and top opportunities, then can ask Flux to help build a roadmap for closing the highest-impact gaps."],
];
type Assessment = Record<string, string | string[]>;
function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) { return <m.div initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .14 }} transition={{ delay, duration: .7, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</m.div>; }
function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) { return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className="flux-kicker text-flux">{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.6rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>; }
const inputClass = "mt-2 w-full rounded-xl border border-ink/15 bg-white px-4 py-3.5 text-sm outline-none transition focus:border-flux focus:ring-2 focus:ring-flux/15";

function AuditForm() {
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [assessment, setAssessment] = useState<Assessment>({});
  const [status, setStatus] = useState<"idle" | "sending" | "error">("idle");
  const submittingRef = useRef(false);
  const score = useMemo(() => {
    const ratings = ["discovery", "journey", "revenue", "operations", "ai"].map(key => Number(assessment[key] || 1));
    return Math.round(ratings.reduce((sum, value) => sum + value, 0) * 4);
  }, [assessment]);
  const band = score <= 40 ? ["Disconnected", "Multiple parts of the customer journey are likely operating in isolation."] : score <= 70 ? ["Developing", "Some foundations are connected, but meaningful gaps remain."] : ["Intelligent", "Your foundations are connected; the opportunity is refinement and scale."];
  const weakest = useMemo(() => ["Discovery", "Customer journey", "Revenue visibility", "System connection", "AI readiness"].map((label, index) => ({ label, value: Number(assessment[["discovery", "journey", "revenue", "operations", "ai"][index]] || 1) })).sort((a, b) => a.value - b.value).slice(0, 2), [assessment]);

  function collectAssessment(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const values: Assessment = {};
    data.forEach((value, key) => { values[key] = value.toString(); });
    setAssessment(values);
    setStep(2);
  }
  async function submitContact(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (submittingRef.current) return;
    submittingRef.current = true;
    setStatus("sending");
    const data = new FormData(event.currentTarget);
    data.append("access_key", ACCESS_KEY);
    data.append("subject", `Flux Business Intelligence Audit — ${String(assessment.business_name || "New submission")}`);
    data.append("from_name", "Flux Business Intelligence Audit");
    data.append("Business Intelligence Score", `${score}/100 — ${band[0]}`);
    Object.entries(assessment).forEach(([key, value]) => data.append(key.replaceAll("_", " "), Array.isArray(value) ? value.join(", ") : value));
    try {
      const response = await fetch("https://api.web3forms.com/submit", { method: "POST", body: data });
      if (!response.ok) throw new Error(`Submission failed with status ${response.status}`);
      const result = await response.json();
      if (!result.success) throw new Error("Submission failed");
      setStep(3); setStatus("idle");
    } catch {
      setStatus("error");
    } finally {
      submittingRef.current = false;
    }
  }
  const rating = (name: string, label: string) => <label className="block"><span className="text-sm font-semibold">{label}</span><select name={name} required className={inputClass} defaultValue=""><option value="" disabled>Select the closest answer</option><option value="1">Not in place</option><option value="2">Mostly manual or inconsistent</option><option value="3">Partly connected</option><option value="4">Connected and measured</option><option value="5">Optimized and improving</option></select></label>;

  return <div className="rounded-[2rem] bg-white p-6 shadow-[0_30px_100px_rgba(6,7,10,.12)] md:p-10">
    <div className="mb-8 flex items-center justify-between"><div><p className="flux-kicker text-flux">Business Intelligence Audit</p><p className="mt-2 text-sm text-ink/50">{step === 1 ? "Step 1 · Assessment" : step === 2 ? "Step 2 · Your score" : "Assessment sent"}</p></div><span className="font-display text-2xl font-medium">{step}/3</span></div>
    {step === 1 ? <form onSubmit={collectAssessment} className="space-y-6">
      <div className="grid gap-5 md:grid-cols-2"><label className="block"><span className="text-sm font-semibold">Business name</span><input name="business_name" required className={inputClass} /></label><label className="block"><span className="text-sm font-semibold">Industry</span><select name="industry" required className={inputClass} defaultValue=""><option value="" disabled>Select industry</option><option>Healthcare</option><option>Home services</option><option>Legal</option><option>Wellness</option><option>Professional services</option><option>Other service business</option></select></label><label className="block"><span className="text-sm font-semibold">Website URL</span><input name="website" type="url" placeholder="https://" required className={inputClass} /></label><label className="block"><span className="text-sm font-semibold">Number of employees</span><select name="employees" required className={inputClass} defaultValue=""><option value="" disabled>Select range</option><option>1–2</option><option>3–10</option><option>11–25</option><option>26–50</option><option>51+</option></select></label></div>
      <label className="block"><span className="text-sm font-semibold">Main challenge</span><select name="main_challenge" required className={inputClass} defaultValue=""><option value="" disabled>Select your main challenge</option><option>Not enough leads</option><option>Leads are not converting</option><option>No follow-up system</option><option>Systems do not talk to each other</option><option>Not sure</option></select></label>
      <div className="grid gap-5 md:grid-cols-2"><label className="block"><span className="text-sm font-semibold">Approximate monthly lead volume</span><select name="monthly_leads" required className={inputClass} defaultValue=""><option value="" disabled>Select range</option><option>0–10</option><option>11–30</option><option>31–100</option><option>101–300</option><option>300+</option></select></label><label className="block"><span className="text-sm font-semibold">Current tools</span><input name="current_tools" placeholder="CRM, booking system, spreadsheets, none…" required className={inputClass} /></label></div>
      <label className="block"><span className="text-sm font-semibold">Biggest growth goal</span><textarea name="growth_goal" required rows={3} className={inputClass} /></label>
      <div className="border-t border-ink/15 pt-6"><p className="mb-5 font-display text-xl font-medium">Score your current system</p><div className="grid gap-5 md:grid-cols-2">{rating("discovery", "Customers can easily find and understand us")}{rating("journey", "Enquiries receive a fast, consistent response")}{rating("revenue", "We can see where opportunities are lost")}{rating("operations", "Our website, CRM, and tools share context")}{rating("ai", "AI systems can understand and recommend us")}</div></div>
      <button type="submit" className="flux-button flux-button-red w-full justify-center">Reveal my score <ArrowUpRight size={16} /></button><p className="text-center text-xs text-ink/45">No contact details are collected in this step.</p>
    </form> : null}
    {step === 2 ? <div><div className="rounded-[1.75rem] bg-ink p-7 text-white md:p-9"><div className="flex items-end justify-between"><div><p className="flux-kicker text-white/45">Estimated score</p><p className="mt-5 font-display text-6xl font-medium">{score}<span className="text-2xl text-white/35">/100</span></p></div><span className="rounded-full bg-flux px-4 py-2 text-xs font-bold uppercase tracking-wider">{band[0]}</span></div><div className="mt-7 h-2 overflow-hidden rounded-full bg-white/15"><m.div initial={{ scaleX: 0 }} animate={{ scaleX: score / 100 }} transition={{ duration: 1 }} className="h-full bg-flux" /></div><p className="mt-6 text-sm leading-7 text-white/60">{band[1]}</p></div><div className="my-7"><p className="text-sm font-semibold">Your first opportunities</p><div className="mt-3 grid gap-3 md:grid-cols-2">{weakest.map(item => <div key={item.label} className="rounded-xl bg-cream p-4 text-sm"><span className="text-flux">●</span> Strengthen {item.label.toLowerCase()}</div>)}</div></div>
      <form onSubmit={submitContact} className="space-y-5 border-t border-ink/15 pt-7"><div><h3 className="font-display text-2xl font-medium">Send your assessment to Flux</h3><p className="mt-2 text-sm leading-6 text-ink/55">Share your details after seeing the score so we can review your answers and help map the highest-impact gaps.</p></div><div className="grid gap-5 md:grid-cols-2"><label><span className="text-sm font-semibold">Name</span><input name="name" required className={inputClass} /></label><label><span className="text-sm font-semibold">Email</span><input name="email" type="email" required className={inputClass} /></label></div><label className="block"><span className="text-sm font-semibold">Phone <span className="font-normal text-ink/40">(optional)</span></span><input name="phone" type="tel" className={inputClass} /></label><input type="checkbox" name="botcheck" aria-hidden="true" aria-label="Leave this field empty" className="hidden" tabIndex={-1} autoComplete="off" /><label className="flex items-start gap-3 text-xs leading-6 text-ink/55"><input type="checkbox" required className="mt-1 accent-flux" />I agree that Flux may contact me about this assessment. My information will only be used to respond to this request.</label><button type="submit" disabled={status === "sending"} className="flux-button flux-button-red w-full justify-center disabled:opacity-60">{status === "sending" ? <><Loader2 className="animate-spin" size={16} /> Sending assessment…</> : <>Send my assessment <ArrowUpRight size={16} /></>}</button>{status === "error" ? <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">The assessment could not be sent. Please check your connection and try again.</p> : null}<button type="button" onClick={() => setStep(1)} className="mx-auto flex items-center gap-2 text-xs font-semibold text-ink/45 hover:text-ink"><RotateCcw size={13} /> Edit assessment answers</button></form>
    </div> : null}
    {step === 3 ? <div className="py-10 text-center"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-flux text-white"><Check size={28} /></span><h3 className="mt-7 font-display text-4xl font-medium">Assessment received.</h3><p className="mx-auto mt-4 max-w-lg text-base leading-8 text-ink/60">Your score was {score}/100. Flux will review your answers and respond within 24 hours with the clearest next opportunity.</p><Link href="/operating-intelligence" className="flux-button flux-button-line mt-8">Explore Operating Intelligence</Link></div> : null}
  </div>;
}

export default function BusinessIntelligenceAuditPage() {
  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><m.div animate={{ x: [0, 60, -25, 0], y: [0, -40, 35, 0], borderRadius: ["40% 60% 65% 35%", "63% 37% 44% 56%", "36% 64% 55% 45%", "40% 60% 65% 35%"] }} transition={{ duration: 20, repeat: Infinity, ease: "easeInOut" }} className="pointer-events-none absolute -right-32 top-24 h-[30rem] w-[30rem] bg-pulse opacity-40 blur-2xl" /><div className="flux-shell relative z-10"><nav className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><span>Business Intelligence Audit</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.18fr_.82fr] lg:items-end lg:py-16"><m.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }}><p className="flux-kicker mb-7 text-flux">Business Intelligence Audit</p><h1 className="font-display text-[clamp(3.4rem,6.2vw,6.5rem)] font-medium leading-[.91] tracking-[-.07em]">Discover where your business is <span className="text-flux">losing opportunities.</span></h1></m.div><m.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Every business has gaps between discovery, response, conversion, and connected operations. This structured assessment shows where you stand across the customer journey, revenue, systems, and AI readiness.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#assessment" className="flux-button flux-button-red">Start your audit <ArrowUpRight size={16} /></a><a href="#measures" className="flux-button flux-button-line">See what it measures</a></div></m.div></div><a href="#problem" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">Understand the gap <ArrowDownRight size={16} /></a></div></section>
    <section id="problem" className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Not always a marketing problem">Another tool rarely fixes a disconnected system.</Heading><div className="mt-14 grid gap-6 lg:grid-cols-2"><Reveal className="space-y-7 rounded-[2rem] bg-cream p-8 text-xl leading-9 text-ink/65 md:p-12"><p>When growth stalls, the instinct is more ads, content, or software. Sometimes that is right. Often it is not.</p><p>Most businesses already have a CRM, website, ad account, and automation. Growth remains difficult because those systems were never designed to work together, and nobody has an honest view of the gaps.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-ink p-8 text-white md:p-12"><p className="flux-kicker text-flux">Before spending more</p><p className="mt-24 font-display text-4xl font-medium">Know exactly where your current system loses opportunity.</p></Reveal></div></div></section>
    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="What the audit is">A scored map of your own business—not generic recommendations.</Heading><div className="mt-14 grid gap-8 lg:grid-cols-2"><Reveal className="text-xl leading-9 text-ink/65"><p>A Business Intelligence Audit evaluates how effectively a company discovers customers, manages the customer journey, converts opportunities, and uses technology to support growth.</p><p className="mt-7">It maps discovery, response, conversion, and follow-up as one connected picture, then identifies the highest-impact improvements from your answers.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-white p-8 md:p-12"><p className="font-display text-3xl font-medium">This is not an SEO audit or marketing audit.</p><p className="mt-6 text-base leading-8 text-ink/60">Those inspect one channel. This assesses the full system a customer moves through, from first search to long-term relationship.</p></Reveal></div></div></section>
    <section id="measures" className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="What the audit evaluates" light>Five areas. One connected Business Intelligence Score.</Heading><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{areas.map(([number, title, question, body], index) => <Reveal key={title} delay={index * .05} className={`flex min-h-[340px] flex-col justify-between rounded-[1.75rem] p-7 ${index === 2 ? "bg-flux" : "border border-white/20"}`}><span className="text-xs font-bold opacity-45">{number}</span><div><h3 className="font-display text-2xl font-medium">{title}</h3><p className="mt-4 font-semibold">{question}</p><p className="mt-4 text-sm leading-7 opacity-55">{body}</p></div></Reveal>)}</div></div></section>
    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Your score">From disconnected to intelligent.</Heading><div className="mt-14 grid gap-4 md:grid-cols-3">{[["0–40", "Disconnected", "Systems operate in isolation and opportunities are likely lost at several stages."], ["41–70", "Developing", "Some systems connect, but meaningful gaps remain in one or two areas."], ["71–100", "Intelligent", "Discovery, response, conversion, and follow-up are connected; focus shifts to scale."]].map(([range, title, body], index) => <Reveal key={title} delay={index * .07} className={`flex min-h-[300px] flex-col justify-between rounded-[2rem] p-8 ${index === 1 ? "bg-pulse-light" : index === 2 ? "bg-flux text-white" : "bg-cream"}`}><span className="font-display text-5xl font-medium">{range}</span><div><h3 className="font-display text-3xl font-medium">{title}</h3><p className="mt-4 text-sm leading-7 opacity-65">{body}</p></div></Reveal>)}</div></div></section>
    <section className="bg-flux py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="How it works" light>Assessment to roadmap in four clear steps.</Heading><div className="mt-14 divide-y divide-white/25 border-y border-white/25">{[["Complete the assessment", "Answer short questions about your business, tools, and customer journey."], ["Receive your score", "See your Business Intelligence Score across five areas."], ["Understand opportunities", "Identify where your answers show the most likely revenue leakage."], ["Build your roadmap", "Map the highest-impact improvements with Flux."]].map(([title, body], index) => <Reveal key={title} className="grid gap-5 py-8 md:grid-cols-[4rem_.4fr_.6fr]"><span className="text-xs font-bold">0{index + 1}</span><h3 className="font-display text-2xl font-medium">{title}</h3><p className="text-white/65">{body}</p></Reveal>)}</div></div></section>
    <section id="assessment" className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Start the assessment">Ready to understand your Business Intelligence Score?</Heading><div className="mt-14 grid gap-10 lg:grid-cols-[.34fr_.66fr]"><Reveal><p className="text-xl leading-9 text-ink/65">Most businesses assume their growth problem is marketing. Often it is connection—and the only way to know is to see where your specific systems stand.</p><p className="mt-7 text-sm leading-7 text-ink/50">Most businesses finish in under ten minutes. You see your estimated score before sharing contact details.</p></Reveal><AuditForm /></div></div></section>
    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Built on Operating Intelligence" light>The audit measures the same connected system Flux builds.</Heading><div className="mt-14 grid gap-4 md:grid-cols-4">{[["Operating Intelligence", "/operating-intelligence"], ["AI Discovery", "/ai-discovery"], ["Revenue Intelligence", "/revenue-intelligence"], ["Customer Progression", "/customer-progression"]].map(([title, href]) => <Link key={title} href={href} className="group flex min-h-[220px] flex-col justify-between border border-white/20 p-7 transition-colors hover:bg-white hover:text-ink"><ArrowUpRight className="ml-auto" /><h3 className="font-display text-2xl font-medium">{title}</h3></Link>)}</div></div></section>
    <section className="bg-cream py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="FAQ">Questions about the Business Intelligence Audit.</Heading><div className="mt-14 divide-y divide-ink/15 border-y border-ink/15">{faqItems.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 items-center justify-center rounded-full border border-ink/15 transition-transform group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>
  </>;
}
