"use client";
import Link from "next/link";
import { m, useScroll, useTransform } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Check, CircleDot, MessageSquare, MoveRight } from "lucide-react";
import { useRef } from "react";
import PlatformEcosystem from "@/components/brand/PlatformEcosystem";

const journey = ["Discovery", "Enquiry", "Response", "Conversation", "Decision", "Purchase", "Relationship"];
const framework = [
  ["01", "Capture Intelligence", "Every form, call, message, or other opportunity lands in one place the team can see. No enquiry disappears into an unmonitored inbox, voicemail, or disconnected channel."],
  ["02", "Response Intelligence", "Fast, consistent response protects initial interest through communication workflows, immediate notifications, and AI assistance for simple acknowledgements that do not require human judgment."],
  ["03", "Journey Intelligence", "The system understands whether someone is a new enquiry, considering options, ready to book, or already a customer—so the next action reflects where that person actually stands."],
  ["04", "Progression Workflows", "Follow-ups, reminders, and educational content move customers forward at the right interval without requiring a person to remember every individual action."],
  ["05", "Relationship Intelligence", "Progression continues after the sale through review requests, retention outreach, and ongoing communication that turns a single purchase into a repeat relationship."],
];
const faqs = [
  ["What is Customer Progression?", "Customer Progression is the process and system businesses use to help customers move from initial awareness through engagement, conversion, and into a long-term relationship, instead of stalling out after the first interaction."],
  ["Why do businesses lose leads after generating enquiries?", "Because most businesses put their effort into generating the enquiry and very little into what happens afterward: response speed, follow-up consistency, and visibility into where a specific customer stands in their decision."],
  ["How does Customer Progression improve conversions?", "By making sure every enquiry is captured, responded to quickly, and followed up with consistently, based on where that customer actually is in their journey, rather than relying on manual effort that varies by who happens to be available."],
  ["Is Customer Progression the same as CRM?", "No. A CRM stores customer information and logs activity. Customer Progression uses that information, along with communication and workflow automation, to actively move a customer forward through their journey."],
  ["How does AI improve customer journeys?", "AI can help understand where a conversation stands, prioritize which opportunities need attention first, and support fast, consistent communication, particularly for straightforward responses that don't require a judgment call from a person."],
  ["What businesses need customer progression systems?", "Any business generating enquiries through more than one channel—calls, forms, and messages—where slow or inconsistent follow-up would mean losing a customer who was otherwise ready to move forward."],
  ["How does automation improve customer relationships?", "By making sure follow-up happens consistently regardless of staff workload, so customers don't experience gaps in communication simply because the business got busy."],
];
const industries = [
  ["Healthcare", "Patient enquiry moves to appointment, post-visit follow-up, and retention through recurring-care reminders.", "/industries/healthcare"],
  ["Home services", "A service request moves to estimate, booking, and ideally a repeat relationship rather than one isolated job.", "/industries/home-services"],
  ["Legal", "An initial consultation moves to formal engagement, where delayed response between consultation and decision creates the greatest risk.", "/industries/legal"],
  ["Wellness", "Initial interest moves to membership or first booking, then retention through consistent communication.", "/industries/wellness"],
];
function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) { return <m.div initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .14 }} transition={{ delay, duration: .7, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</m.div>; }
function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) { return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className="flux-kicker text-flux">{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.6rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>; }
function ProgressionVisual() { return <div className="relative min-h-[430px] overflow-hidden rounded-[2rem] bg-ink p-8 text-white"><m.div animate={{ rotate: 360 }} transition={{ duration: 34, repeat: Infinity, ease: "linear" }} className="absolute -right-24 -top-24 h-80 w-80 rounded-[42%_58%_64%_36%] border border-white/15" /><div className="relative z-10 flex min-h-[366px] flex-col justify-between"><p className="flux-kicker text-white/45">Live journey</p><div className="space-y-3">{["New enquiry captured", "Response sent in 00:42", "Next action assigned"].map((item, index) => <m.div key={item} animate={{ x: [0, 8, 0] }} transition={{ delay: index * .6, duration: 4, repeat: Infinity }} className="flex items-center gap-4 rounded-2xl border border-white/15 bg-white/10 p-4 backdrop-blur"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-flux"><Check size={14} /></span><span className="text-sm">{item}</span></m.div>)}</div><div className="flex items-center gap-3 text-sm text-white/55"><CircleDot className="text-flux" /> Interest keeps moving</div></div></div>; }

export default function CustomerProgressionPage() {
  const frameworkRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: frameworkRef, offset: ["start end", "end start"] });
  const lineScale = useTransform(scrollYProgress, [.1, .82], [0, 1]);
  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><m.div animate={{ x: [0, 60, -25, 0], y: [0, -38, 42, 0], borderRadius: ["38% 62% 57% 43%", "64% 36% 45% 55%", "43% 57% 66% 34%", "38% 62% 57% 43%"] }} transition={{ duration: 20, repeat: Infinity, ease: "easeInOut" }} className="pointer-events-none absolute -right-32 top-24 h-[30rem] w-[30rem] bg-pulse opacity-40 blur-2xl" /><div className="flux-shell relative z-10"><nav aria-label="Breadcrumb" className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/solutions">Solutions</Link><span className="mx-2">/</span><span>Customer Progression</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.18fr_.82fr] lg:items-end lg:py-16"><m.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .82 }}><p className="flux-kicker mb-7 text-flux">Customer Progression</p><h1 className="max-w-6xl font-display text-[clamp(3.35rem,6.1vw,6.4rem)] font-medium leading-[.91] tracking-[-.07em]">Getting attention was never the hard part. <span className="text-flux">Customer Progression is.</span></h1></m.div><m.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15, duration: .72 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Every week, your business generates enquiries. Most interest never becomes revenue—not because the customer was not interested, but because nobody moved them forward.</p><p className="mt-5 text-lg leading-8 text-ink/65">Customer Progression connects communication, workflows, and intelligence so interest does not stall after the first interaction.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/business-intelligence-audit" className="flux-button flux-button-red">Get a free Customer Journey Assessment <ArrowUpRight size={16} /></Link><a href="#framework" className="flux-button flux-button-line">See how the framework works</a></div></m.div></div><a href="#growth-problem" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">Follow the journey <span className="flex h-10 w-10 items-center justify-center rounded-full border border-ink/15 transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-500 group-hover:translate-y-1 group-hover:bg-ink group-hover:text-white"><ArrowDownRight size={16} /></span></a></div></section>

    <PlatformEcosystem variant="intelligence" />

    <section id="growth-problem" className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="The growth problem">The breakdown happens after someone raises their hand.</Heading><div className="mt-14 grid gap-10 lg:grid-cols-[.56fr_.44fr]"><Reveal className="space-y-7 text-xl leading-9 text-ink/65"><p>Businesses spend real money generating attention through ads, content, SEO, and referrals. Often it works: people visit, fill out the form, and make the call.</p><p>Then nothing happens. Not because the person changed their mind, but because the business did not give them a reason to keep moving. Slow response or missing follow-up pushes them toward the competitor who does respond.</p><p>Most businesses focus on discovery and enquiry, then assume the remaining journey will take care of itself. It rarely does.</p><p>The problem being attacked with more marketing often lives downstream—in the space between interest and becoming a customer. That is where Customer Progression operates.</p></Reveal><ProgressionVisual /></div><div className="mt-16 grid gap-2 md:grid-cols-7">{journey.map((item, index) => <Reveal key={item} delay={index * .04} className="group flex min-h-[130px] flex-col justify-between rounded-2xl bg-cream p-5 transition-colors duration-500 hover:bg-flux hover:text-white"><span className="text-xs font-bold opacity-40">0{index + 1}</span><div className="flex items-center justify-between gap-2"><span className="font-display text-lg font-medium">{item}</span>{index < journey.length - 1 ? <MoveRight size={16} /> : null}</div></Reveal>)}</div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="What it is">A system that keeps interest moving toward a relationship.</Heading><div className="mt-14 grid gap-6 lg:grid-cols-2"><Reveal className="rounded-[2rem] bg-white p-8 md:p-12"><p className="text-xl leading-9 text-ink/68">Customer Progression helps customers move from initial awareness through engagement, conversion, and into a long-term relationship rather than stalling after first contact.</p><p className="mt-7 text-xl leading-9 text-ink/68">It is needed wherever calls, forms, and chat messages are handled by different people or processes without visibility into one another.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-ink p-8 text-white md:p-12"><p className="text-xl leading-9 text-white/65">Every enquiry is captured, answered quickly, understood by its current decision stage, and supported with the right follow-up at the right time.</p><p className="mt-8 font-display text-3xl font-medium">Recovering opportunities already paid for is often faster and less expensive than generating more leads.</p></Reveal></div></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Why journeys break" light>The customer experiences one relationship. Your systems see separate events.</Heading><div className="mt-14 grid gap-12 lg:grid-cols-[.6fr_.4fr]"><Reveal className="space-y-7 text-xl leading-9 text-white/65"><p>The website knows a visitor spent ten minutes on pricing. The CRM records a call two days later. The team member taking that call cannot see the page visit, so the conversation starts from zero.</p><p>The customer notices when the relationship does not feel connected. More channels should create more opportunities, but without a shared system they create more places for people to disappear unnoticed.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-flux p-8"><MessageSquare size={30} /><p className="mt-24 font-display text-4xl font-medium">One customer.<br />Many disconnected signals.<br />No shared context.</p></Reveal></div></div></section>

    <section id="framework" ref={frameworkRef} className="relative overflow-hidden bg-cream py-24 md:py-36"><div className="pointer-events-none absolute -left-44 top-1/3 h-96 w-96 rounded-full bg-pulse/40 blur-3xl" /><div className="flux-shell relative z-10"><Heading eyebrow="The Flux framework">Five connected layers that move customers forward.</Heading><div className="relative mt-16"><div className="absolute bottom-0 left-[19px] top-0 w-px bg-ink/15 md:left-1/2" /><m.div style={{ scaleY: lineScale, transformOrigin: "top" }} className="absolute bottom-0 left-[19px] top-0 w-px bg-flux md:left-1/2" />{framework.map(([number, title, body], index) => <Reveal key={title} className="relative mb-8 grid gap-6 pl-14 md:grid-cols-2 md:pl-0"><span className="absolute left-0 top-8 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-flux text-xs font-bold text-white md:left-1/2 md:-translate-x-1/2">{number}</span><article className={`rounded-[2rem] border border-ink/10 bg-white p-8 shadow-[0_20px_70px_rgba(6,7,10,.06)] md:p-11 ${index % 2 ? "md:col-start-2 md:ml-12" : "md:mr-12"}`}><h3 className="font-display text-3xl font-medium md:text-4xl">{title}</h3><p className="mt-6 text-base leading-8 text-ink/60">{body}</p></article></Reveal>)}</div></div></section>

    <section className="bg-flux py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Powered by Operating Intelligence" light>Discovery finds the customer. Intelligence sees the gap. Progression moves them forward.</Heading><div className="mt-14 grid gap-10 border-t border-white/25 pt-8 lg:grid-cols-[.62fr_.38fr]"><Reveal className="space-y-7 text-xl leading-9 text-white/70"><p>Customer Progression sits after AI Discovery and alongside Revenue Intelligence inside Flux&apos;s Operating Intelligence system.</p><p>AI Discovery gets a customer to find the business. Revenue Intelligence shows where opportunities succeed or fail. Customer Progression translates that visibility into response, follow-up, and communication.</p></Reveal><Link href="/operating-intelligence" className="group flex min-h-[240px] flex-col justify-between rounded-[2rem] bg-white p-8 text-ink transition-transform duration-500 hover:-translate-y-2"><ArrowUpRight className="ml-auto transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /><p className="font-display text-3xl font-medium">Explore Operating Intelligence</p></Link></div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Progression by industry">Different customer journeys. The same need for movement.</Heading><div className="mt-14 grid gap-4 md:grid-cols-2">{industries.map(([title, body, href], index) => <Reveal key={title} delay={index * .05}><Link href={href} className="group flex min-h-[270px] flex-col justify-between rounded-[2rem] bg-white p-8 transition-transform duration-500 hover:-translate-y-2"><ArrowUpRight className="ml-auto text-flux transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /><div><h3 className="font-display text-3xl font-medium">{title}</h3><p className="mt-5 max-w-xl text-sm leading-7 text-ink/60">{body}</p></div></Link></Reveal>)}</div><p className="mt-10 max-w-4xl text-lg leading-8 text-ink/65">Across every industry, interest that is not actively moved forward tends to stall.</p></div></section>

    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Customer Progression vs CRM">The CRM stores the relationship. Progression moves it.</Heading><div className="mt-14 overflow-hidden rounded-[2rem] border border-ink/15"><div className="grid grid-cols-2 border-b border-ink/15 bg-cream p-5 font-display text-xl font-medium md:p-7"><span>Traditional CRM</span><span>Customer Progression</span></div>{[["Stores contacts", "Guides customer movement"], ["Tracks activity", "Understands intent"], ["Records what happened", "Improves what happens next"], ["Requires manual follow-up", "Creates workflows that move customers forward automatically"]].map(([left, right]) => <div key={left} className="grid grid-cols-2 border-b border-ink/15 p-5 text-sm leading-6 last:border-0 md:p-7 md:text-base"><span className="pr-5 text-ink/55">{left}</span><span className="font-semibold">{right}</span></div>)}</div><p className="mt-9 max-w-4xl text-lg leading-8 text-ink/65">A CRM is often the storage layer inside a Customer Progression system. The movement layer is the workflow built on top of it.</p></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Related systems" light>Continue through the connected operating system.</Heading><div className="mt-14 grid border-t border-white/20 md:grid-cols-2 lg:grid-cols-3">{[["AI Discovery", "/ai-discovery"], ["Revenue Intelligence", "/revenue-intelligence"], ["Patient Revenue System", "/patient-revenue-system"], ["Patient Revenue System for Clinics", "/clinics"], ["Operating Intelligence", "/operating-intelligence"], ["Business Intelligence Audit", "/business-intelligence-audit"]].map(([title, href]) => <Link key={title} href={href} className="group flex min-h-[220px] flex-col justify-between border-b border-white/20 p-7 transition-colors duration-500 hover:bg-white hover:text-ink md:border-r"><ArrowUpRight className="ml-auto transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /><h3 className="font-display text-2xl font-medium">{title}</h3></Link>)}</div></div></section>

    <section className="bg-cream py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="FAQ">Questions about moving customers forward.</Heading><div className="mt-14 divide-y divide-ink/15 border-y border-ink/15">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-ink/15 transition-transform duration-500 group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>

    <section className="relative overflow-hidden bg-flux py-24 text-white md:py-36"><m.div animate={{ rotate: 360 }} transition={{ duration: 38, repeat: Infinity, ease: "linear" }} className="absolute -right-48 -top-48 h-[38rem] w-[38rem] rounded-[38%_62%_58%_42%] border border-white/20" /><div className="flux-shell relative z-10"><p className="flux-kicker text-white/60">Business Intelligence Assessment</p><Reveal><h2 className="mt-7 max-w-6xl font-display text-[clamp(3rem,5.5vw,5.7rem)] font-medium leading-[.95] tracking-[-.06em]">See where customers stall between enquiry and conversion.</h2></Reveal><p className="mt-9 max-w-3xl text-xl leading-9 text-white/70">Review the journey, ownership, systems, and follow-up before deciding which part needs to change.</p><Link href="/business-intelligence-audit" className="flux-button mt-10 bg-white text-ink">Start your assessment <ArrowUpRight size={16} /></Link></div></section>
  </>;
}
