"use client";
import Link from "next/link";
import { m, useScroll, useTransform } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Bot, BrainCircuit, Search, Workflow, ChartNoAxesCombined } from "@/components/ui/animated-icons";
import { useRef } from "react";
import PlatformEcosystem from "@/components/brand/PlatformEcosystem";

const layers = [
  ["01", "Discovery Intelligence", "How customers find the business across traditional search, AI search, and digital reputation.", "/ai-discovery", Search],
  ["02", "Revenue Intelligence", "How the business sees where opportunities originate, convert, stall, and disappear.", "/revenue-intelligence", ChartNoAxesCombined],
  ["03", "Customer Progression", "How each customer moves from enquiry through decision, purchase, and relationship.", "/customer-progression", ArrowUpRight],
  ["04", "Automation Intelligence", "How workflows and AI handle repeatable tasks while preserving human judgment where it matters.", "/services/make-zapier-automation", Workflow],
  ["05", "Decision Intelligence", "How connected insight identifies what to improve next instead of relying on instinct.", "/business-intelligence-audit", BrainCircuit],
];
const faqs = [
  ["What is Operating Intelligence?", "Operating Intelligence is the ability of a business to connect its data, customer interactions, systems, workflows, and AI capabilities to make better decisions, operate more efficiently, and continuously improve growth."],
  ["Why do businesses need Operating Intelligence?", "Because most businesses now run on several disconnected systems—a CRM, website, marketing tools, and automation—that each hold part of the picture without sharing it with the others."],
  ["What is the difference between Business Intelligence and Operating Intelligence?", "Business Intelligence uses dashboards and reports to understand what happened. Operating Intelligence goes further by connecting insight to the systems and workflows that actively improve how the business operates."],
  ["What is the difference between automation and Operating Intelligence?", "Automation performs a specific task. Operating Intelligence determines when automation should run, what context it should use, and how that action fits into the full customer journey."],
  ["How does AI impact business operations?", "AI helps businesses understand behavior, decide faster, and act in real time, but only when underlying data and systems give it accurate, complete information."],
  ["Is Operating Intelligence the same as automation?", "No. Automation is one layer. Operating Intelligence also connects discovery, revenue visibility, customer progression, and decision-making."],
  ["How can a company become AI ready?", "By connecting existing systems and data so information flows consistently and any AI tool has accurate context to work with."],
  ["What is an intelligent business system?", "It is a system where discovery, customer data, communication, automation, and decisions connect so the business can see where opportunities are won or lost and continuously improve."],
];
function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) { return <m.div initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .14 }} transition={{ delay, duration: .7, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</m.div>; }
function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) { return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className="flux-kicker text-flux">{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.6rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>; }
function SystemVisual() { return <div className="relative min-h-[440px] overflow-hidden rounded-[2rem] bg-ink text-white">{[0, 1, 2].map(index => <m.div key={index} animate={{ rotate: index % 2 ? -360 : 360 }} transition={{ duration: 24 + index * 9, repeat: Infinity, ease: "linear" }} className="absolute left-1/2 top-1/2 rounded-[43%_57%_62%_38%] border border-white/15" style={{ width: 170 + index * 105, height: 170 + index * 105, marginLeft: -(170 + index * 105) / 2, marginTop: -(170 + index * 105) / 2 }} />)}<m.div animate={{ borderRadius: ["40% 60% 65% 35%", "65% 35% 44% 56%", "35% 65% 58% 42%", "40% 60% 65% 35%"] }} transition={{ duration: 9, repeat: Infinity }} className="absolute left-1/2 top-1/2 flex h-40 w-40 -translate-x-1/2 -translate-y-1/2 items-center justify-center bg-flux"><Bot size={34} /></m.div>{["Discover", "Understand", "Progress", "Improve"].map((item, index) => <m.span key={item} animate={{ y: [0, -9, 0] }} transition={{ duration: 4 + index, repeat: Infinity }} className="absolute rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs backdrop-blur" style={{ left: `${10 + (index % 2) * 64}%`, top: `${15 + Math.floor(index / 2) * 68}%` }}>{item}</m.span>)}</div>; }

export default function OperatingIntelligencePage() {
  const frameworkRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: frameworkRef, offset: ["start end", "end start"] });
  const lineScale = useTransform(scrollYProgress, [.1, .82], [0, 1]);
  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><m.div animate={{ x: [0, 65, -30, 0], y: [0, -40, 35, 0], borderRadius: ["38% 62% 56% 44%", "65% 35% 43% 57%", "44% 56% 66% 34%", "38% 62% 56% 44%"] }} transition={{ duration: 20, repeat: Infinity }} className="pointer-events-none absolute -right-32 top-24 h-[31rem] w-[31rem] bg-pulse opacity-40 blur-2xl" /><div className="flux-shell relative z-10"><nav className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/philosophy">Why Flux</Link><span className="mx-2">/</span><span>Operating Intelligence</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.18fr_.82fr] lg:items-end lg:py-16"><m.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }}><p className="flux-kicker mb-7 text-flux">Operating Intelligence</p><h1 className="font-display text-[clamp(3.4rem,6.25vw,6.6rem)] font-medium leading-[.91] tracking-[-.07em]">The future of how businesses <span className="text-flux">grow.</span></h1></m.div><m.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Most businesses have more technology than ever, yet growth still feels harder because those systems were not built to work together.</p><p className="mt-5 text-lg leading-8 text-ink/65">Flux connects discovery, revenue visibility, communication, automation, and decision-making into one intelligent foundation.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/business-intelligence-audit" className="flux-button flux-button-red">Measure your score <ArrowUpRight size={16} /></Link><a href="#framework" className="flux-button flux-button-line">Explore Flux systems</a></div></m.div></div><a href="#new-era" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">Explore the shift <ArrowDownRight size={16} /></a></div></section>

    <PlatformEcosystem variant="intelligence" />

    <section id="new-era" className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="A new business era">Competitive advantage has moved from location, to visibility, to intelligence.</Heading><div className="mt-14 grid gap-4 md:grid-cols-3">{[["Era 1", "Physical Business", "Location decided who found you. Being present where customers already were was most of the battle."], ["Era 2", "Digital Business", "Websites, advertising, and search rankings shifted advantage toward whoever could be found online."], ["Era 3", "Intelligent Business", "Advantage now belongs to businesses whose tools share context, respond faster, and improve continuously."]].map(([era, title, body], index) => <Reveal key={era} delay={index * .07} className={`flex min-h-[350px] flex-col justify-between rounded-[2rem] p-8 ${index === 2 ? "bg-flux text-white" : index === 1 ? "bg-pulse-light" : "bg-cream"}`}><span className="flux-kicker opacity-50">{era}</span><div><h3 className="font-display text-4xl font-medium">{title}</h3><p className="mt-6 text-sm leading-7 opacity-65">{body}</p></div></Reveal>)}</div><p className="mt-10 max-w-4xl text-xl leading-9 text-ink/65">Each era still matters. What changed is that physical and digital presence are no longer sufficient without systems that actually talk to each other.</p></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Not a lack of technology">More software usually adds another disconnected island.</Heading><div className="mt-14 grid gap-10 lg:grid-cols-[.56fr_.44fr]"><Reveal className="space-y-7 text-xl leading-9 text-ink/65"><p>Growing service businesses have CRMs, websites, marketing tools, analytics, automation, and increasingly AI layered on top.</p><p>The gap lives between them. The CRM does not know what a visitor viewed. Marketing cannot see which leads sales closed. Automation runs without context from the customer journey.</p><p>Each tool performs its individual job, yet the business cannot confidently answer where its best customers come from, where interested people go quiet, or what to fix next.</p><p>The businesses gaining advantage are not buying the most software. They are connecting what they already have.</p></Reveal><SystemVisual /></div></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="What it is" light>The connected layer between software ownership and an intelligent business.</Heading><div className="mt-14 grid gap-6 lg:grid-cols-2"><Reveal className="rounded-[2rem] border border-white/20 p-8 md:p-12"><p className="text-xl leading-9 text-white/65">Operating Intelligence connects data, customer interactions, systems, workflows, and AI capabilities so a business can decide better, operate efficiently, and continuously improve growth.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-flux p-8 md:p-12"><p className="text-xl leading-9 text-white/75">It does not add another tool. It connects the tools that already exist so the intelligence generated by every interaction can be seen and acted on.</p><p className="mt-8 font-display text-3xl font-medium">A collection of software becomes one coherent operating system.</p></Reveal></div></div></section>

    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Traditional systems vs Operating Intelligence">Start with how information should move—not which tool to buy next.</Heading><div className="mt-14 grid overflow-hidden rounded-[2rem] border border-ink/15 md:grid-cols-2"><Reveal className="p-8 md:p-12"><p className="flux-kicker text-ink/40">Traditional systems</p><p className="mt-10 text-xl leading-9 text-ink/65">Tools are added one at a time to solve urgent problems. Separate teams manage separate data, and each reasonable purchase adds another isolated view.</p></Reveal><Reveal delay={.08} className="bg-ink p-8 text-white md:p-12"><p className="flux-kicker text-flux">Operating Intelligence</p><p className="mt-10 text-xl leading-9 text-white/65">Information moves through the business around a shared understanding of the customer, so every system and team can act with the context created elsewhere.</p></Reveal></div></div></section>

    <section id="framework" ref={frameworkRef} className="relative overflow-hidden bg-cream py-24 md:py-36"><div className="pointer-events-none absolute -left-44 top-1/3 h-96 w-96 rounded-full bg-pulse/40 blur-3xl" /><div className="flux-shell relative z-10"><Heading eyebrow="The Flux framework">Five layers. One intelligent operating foundation.</Heading><div className="relative mt-16"><div className="absolute bottom-0 left-[19px] top-0 w-px bg-ink/15 md:left-1/2" /><m.div style={{ scaleY: lineScale, transformOrigin: "top" }} className="absolute bottom-0 left-[19px] top-0 w-px bg-flux md:left-1/2" />{layers.map(([number, title, body, href, Icon], index) => { const LayerIcon = Icon; return <Reveal key={title as string} className="relative mb-8 grid gap-6 pl-14 md:grid-cols-2 md:pl-0"><span className="absolute left-0 top-8 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-flux text-xs font-bold text-white md:left-1/2 md:-translate-x-1/2">{number as string}</span><Link href={href as string} className={`group rounded-[2rem] border border-ink/10 bg-white p-8 shadow-[0_20px_70px_rgba(6,7,10,.06)] transition-transform duration-500 hover:-translate-y-2 md:p-11 ${index % 2 ? "md:col-start-2 md:ml-12" : "md:mr-12"}`}><div className="flex justify-between"><LayerIcon /><ArrowUpRight className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div><h3 className="mt-16 font-display text-3xl font-medium md:text-4xl">{title as string}</h3><p className="mt-6 text-base leading-8 text-ink/60">{body as string}</p></Link></Reveal>; })}</div><p className="mt-10 max-w-4xl text-xl leading-9 text-ink/65">Each layer works alone. The advantage compounds when all five share context and act as one system.</p></div></section>

    <section className="bg-flux py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Beyond digital transformation" light>Having modern tools is not the same as operating intelligently.</Heading><div className="mt-14 grid gap-8 lg:grid-cols-2"><Reveal className="text-xl leading-9 text-white/70"><p>Digital transformation focuses on adoption: websites, CRMs, cloud software, and automation platforms.</p><p className="mt-7">A business can adopt every modern tool and remain just as disconnected—only with more expensive software running the disconnection.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-white p-8 text-ink md:p-12"><p className="font-display text-4xl font-medium">Digital transformation asks whether you have the tools.</p><p className="mt-8 font-display text-4xl font-medium text-flux">Operating Intelligence asks whether they make the business smarter.</p></Reveal></div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="For service businesses">Different operations. The same connected advantage.</Heading><div className="mt-14 grid gap-4 md:grid-cols-2">{[["Healthcare", "Connect patient calls, booking, response, follow-up, and visibility across the full patient journey.", "/industries/healthcare"], ["Home services", "Connect quote sources to jobs that close and keep follow-up consistent when crews are busy.", "/industries/home-services"], ["Legal", "Track long consultation cycles so prospects do not go cold between first conversation and engagement.", "/industries/legal"], ["Wellness", "Connect acquisition to memberships, appointments, retention, and repeat relationships.", "/industries/wellness"]].map(([title, body, href], index) => <Reveal key={title} delay={index * .05}><Link href={href} className="group flex min-h-[270px] flex-col justify-between rounded-[2rem] bg-white p-8 transition-transform duration-500 hover:-translate-y-2"><ArrowUpRight className="ml-auto text-flux" /><div><h3 className="font-display text-3xl font-medium">{title}</h3><p className="mt-5 text-sm leading-7 text-ink/60">{body}</p></div></Link></Reveal>)}</div></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Why AI makes it necessary" light>AI is only as useful as the connected context beneath it.</Heading><div className="mt-14 grid gap-12 lg:grid-cols-[.62fr_.38fr]"><Reveal className="space-y-7 text-xl leading-9 text-white/65"><p>An AI responding to a missed call needs to know what the caller asked. Lead prioritization needs CRM and website behavior. Follow-up drafting needs the customer&apos;s current journey stage.</p><p>None of that works when data lives across five systems that cannot share information.</p><p>AI increases the need for structured information and connected business knowledge. Operating Intelligence creates the coherent foundation AI needs to become genuinely useful.</p></Reveal><Reveal delay={.08} className="flex min-h-[360px] flex-col justify-between rounded-[2rem] bg-flux p-8"><Bot size={34} /><p className="font-display text-4xl font-medium">AI readiness starts with connected operations—not another AI tool.</p></Reveal></div></div></section>

    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="How Flux builds it">Map, identify, connect, implement, improve.</Heading><div className="mt-14 divide-y divide-ink/15 border-y border-ink/15">{[["Understand current operations", "Map discovery, communication, conversion, and follow-up around existing tools."], ["Identify gaps", "Find where information stops flowing, response slows, and opportunity disappears."], ["Connect systems", "Build integrations and workflows so tools share useful context."], ["Build intelligence layers", "Prioritize discovery, revenue, progression, or automation by highest impact."], ["Continuously improve", "Adjust the system as the business changes so intelligence remains trusted."]].map(([title, body], index) => <Reveal key={title} className="grid gap-5 py-8 md:grid-cols-[4rem_.4fr_.6fr]"><span className="text-xs font-bold text-flux">0{index + 1}</span><h3 className="font-display text-2xl font-medium">{title}</h3><p className="text-ink/60">{body}</p></Reveal>)}</div></div></section>

    <section className="bg-cream py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="FAQ">Questions about Operating Intelligence.</Heading><div className="mt-14 divide-y divide-ink/15 border-y border-ink/15">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 items-center justify-center rounded-full border border-ink/15 transition-transform group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>

    <section className="relative overflow-hidden bg-flux py-24 text-white md:py-36"><m.div animate={{ rotate: 360 }} transition={{ duration: 38, repeat: Infinity, ease: "linear" }} className="absolute -right-48 -top-48 h-[38rem] w-[38rem] rounded-[38%_62%_58%_42%] border border-white/20" /><div className="flux-shell relative z-10"><p className="flux-kicker text-white/60">Business Intelligence Audit</p><Reveal><h2 className="mt-7 max-w-6xl font-display text-[clamp(3rem,5.5vw,5.7rem)] font-medium leading-[.95] tracking-[-.06em]">Measure your Business Intelligence Score.</h2></Reveal><p className="mt-9 max-w-3xl text-xl leading-9 text-white/70">See where you stand across discovery, customer journey, revenue, operations, and AI readiness before spending more on leads that may leak through the same gaps.</p><Link href="/business-intelligence-audit" className="flux-button mt-10 bg-white text-ink">Start your assessment <ArrowUpRight size={16} /></Link></div></section>
  </>;
}
