import OperatingIntelligencePage from "@/components/operating-intelligence/OperatingIntelligencePage";
import { generateMeta } from "@/lib/seo";
import { SITE } from "@/lib/constants";
export const metadata = generateMeta({ absoluteTitle: "Operating Intelligence | The Future Of Intelligent Business Systems | Flux", description: "Flux builds operating intelligence systems that connect customer discovery, revenue intelligence, automation, data, and AI capabilities to help businesses grow in the AI era.", socialTitle: "Operating Intelligence: The Future of How Businesses Grow", socialDescription: "Businesses don't need more disconnected tools, they need intelligence connecting everything they already have. See how Flux builds the connected system underneath modern growth.", twitterTitle: "What Is Operating Intelligence?", twitterDescription: "More technology hasn't made growth easier for most businesses. Here's why the fix isn't another tool, it's connecting the ones you already have.", path: "/operating-intelligence" });
const faqs = [
  ["What is Operating Intelligence?", "Operating Intelligence is the ability of a business to connect its data, customer interactions, systems, workflows, and AI capabilities to make better decisions, operate more efficiently, and continuously improve growth."],
  ["Why do businesses need Operating Intelligence?", "Because most businesses now run on several disconnected systems that each hold part of the picture without sharing it with the others, making it difficult to see where opportunities are actually being won or lost."],
  ["What is the difference between Business Intelligence and Operating Intelligence?", "Business Intelligence is about understanding information, typically through dashboards and reports that show what happened. Operating Intelligence goes further, using that information to actively improve how the business operates."],
  ["What is the difference between automation and Operating Intelligence?", "Automation performs a specific task. Operating Intelligence is the broader connected system that determines when automation should run, what information it should act on, and how it fits into the business's full customer journey."],
  ["How does AI impact business operations?", "AI increases the ability of businesses to understand customer behavior, make faster decisions, and act on information in real time, but only when the underlying data and systems are connected well enough for AI to work with accurate, complete information."],
  ["Is Operating Intelligence the same as automation?", "No. Automation is one component within Operating Intelligence, specifically the layer that handles well-defined, repeatable tasks. Operating Intelligence also includes discovery, revenue visibility, customer progression, and decision-making."],
  ["How can a company become AI ready?", "By connecting its existing systems and data so that information flows consistently between them, giving any AI tool added later accurate, complete context to work with."],
  ["What is an intelligent business system?", "An intelligent business system is one where discovery, customer data, communication, automation, and decision-making are connected, so the business can see clearly where opportunities are won or lost and continuously improve based on that visibility."],
];
const schemas = [
  { "@context": "https://schema.org", "@type": "Organization", name: "Flux Media Creations", url: SITE.url, description: "Flux is an Operating Intelligence Company that connects customer discovery, revenue intelligence, customer progression, automation, and AI capabilities into one intelligent business system." },
  { "@context": "https://schema.org", "@type": "WebPage", name: "Operating Intelligence", url: `${SITE.url}/operating-intelligence`, description: "Operating Intelligence is the ability of a business to connect its data, customer interactions, systems, workflows, and AI capabilities to make better decisions, operate more efficiently, and continuously improve growth.", isPartOf: { "@type": "WebSite", url: SITE.url } },
  { "@context": "https://schema.org", "@type": "Service", name: "Operating Intelligence Systems", provider: { "@type": "Organization", name: "Flux Media Creations" }, description: "Connected business systems combining discovery intelligence, revenue intelligence, customer progression, automation, and decision intelligence into one intelligent operating foundation.", serviceType: "Business Operating System", areaServed: "United States" },
  { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SITE.url }, { "@type": "ListItem", position: 2, name: "Why Flux", item: `${SITE.url}/why-flux` }, { "@type": "ListItem", position: 3, name: "Operating Intelligence", item: `${SITE.url}/operating-intelligence` }] },
  { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
  { "@context": "https://schema.org", "@type": "ItemList", name: "The Flux Operating Intelligence Framework", itemListElement: ["Discovery Intelligence", "Revenue Intelligence", "Customer Progression", "Automation Intelligence", "Decision Intelligence"].map((name, index) => ({ "@type": "ListItem", position: index + 1, name })) },
];
export default function Page() { return <>{schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}<OperatingIntelligencePage /></>; }
