import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { generateMeta } from "@/lib/seo";

const reportHref = "/reports/service-business-website-growth-report-2026";

export const metadata: Metadata = generateMeta({
  absoluteTitle: "Service Business Website Growth Strategy for 2026 | Flux Media Creations",
  description: "Learn how service businesses can turn their website into a growth system through visibility, trust, conversion, automation, and faster follow-up.",
  path: "/blog/service-business-website-growth-strategy-2026",
  image: "/images/reports/service-business-growth-report-og.png",
});

const sections = [
  ["The website has a new job", ["A website once functioned primarily as a digital business card. In 2026, customers expect it to answer deeper questions: Can I trust this company? Have they helped people like me? Is the next step clear? How quickly will someone respond?", "A growth-focused website supports the journey from discovery and research through trust, enquiry, follow-up, and the purchase decision. It succeeds when it creates business opportunities—not simply when it looks polished."]],
  ["Start with customer clarity", ["Many service-business websites talk about years of experience and quality service before explaining the customer problem they solve. Strong positioning reverses that order. Visitors should quickly understand who the business helps, what result it provides, why it is credible, and what to do next.", "Every important page needs a deliberate conversion path: request a consultation, schedule an appointment, get a quote, contact the team, or download a useful guide."]],
  ["Build visibility around intent", ["Potential customers often search for a solution rather than a company name. Dedicated service and service-area pages help search engines and people understand the exact offer, location, and relevance.", "Local SEO also depends on real-business signals: accurate Google Business Profile information, useful service descriptions, reviews, photos, consistent details, and evidence that the company actively serves customers."]],
  ["Make trust specific", ["Generic claims create very little confidence. Reviews that describe the service, response, and outcome are more persuasive than a simple “great service.” Case studies are stronger when they show the challenge, solution, process, and result.", "Team visibility, expertise, values, certifications, professional design, and consistent messaging reduce the uncertainty customers feel before making contact."]],
  ["Protect every enquiry", ["A customer who submits a form may contact several businesses. Fast confirmation and clear next steps can protect the opportunity while the team prepares a human response.", "Automation can support acknowledgement, scheduling, reminders, and measured follow-up across day one, day three, and day seven. The goal is not to replace people; it is to help the business respond reliably."]],
  ["Design mobile-first and measure what matters", ["Most customers discover local businesses on mobile devices. Calls, forms, booking options, and location details must be quick to find, while optimized images, clean code, and simple page structure protect performance.", "Useful measurement connects website behavior to enquiries and progression. Traffic alone is not the outcome; the objective is a clearer view of how attention becomes opportunity."]],
];

export default function WebsiteGrowthStrategyArticle() {
  return <main className="bg-[#F4F4F1]"><section className="bg-[#050608] pb-20 pt-32 text-white md:pb-28 md:pt-40"><div className="flux-shell"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#DB3826]">Business Growth · 10 min read</p><h1 className="mt-7 max-w-6xl font-display text-[clamp(3.4rem,6.5vw,6.8rem)] font-medium leading-[.91] tracking-[-.07em]">Service Business Website Growth Strategy for 2026</h1><p className="mt-8 max-w-3xl text-lg leading-8 text-white/60">How local businesses can connect visibility, trust, conversion, automation, and measurement into one practical customer growth system.</p></div></section><section className="py-16 md:py-24"><article className="flux-shell grid gap-12 lg:grid-cols-[1fr_320px]"><div className="max-w-3xl"><div className="relative mb-12 aspect-[1200/630] overflow-hidden rounded-[2rem]"><Image src="/images/reports/service-business-growth-report-og.png" alt="2026 Service Business Website Growth Report" fill priority className="object-cover" /></div><p className="text-xl leading-9 text-black/65">For service businesses, visibility matters—but visibility without confidence, an easy next step, and timely follow-up rarely creates growth. The modern website must coordinate the complete customer journey.</p>{sections.map(([heading, paragraphs]) => <section key={heading as string} className="mt-14 border-t border-black/15 pt-7"><h2 className="font-display text-3xl font-medium tracking-[-.04em] md:text-5xl">{heading as string}</h2><div className="mt-6 space-y-5 text-base leading-8 text-black/60">{(paragraphs as string[]).map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div></section>)}<div className="mt-16 rounded-[2rem] bg-[#383B7C] p-8 text-white md:p-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#AEC6FA]">Free authority report</p><h2 className="mt-5 font-display text-3xl font-medium md:text-5xl">Continue with the full 2026 research.</h2><p className="mt-5 text-base leading-8 text-white/65">Get the frameworks, priorities, and practical recommendations in one downloadable resource.</p><Link href={reportHref} className="flux-button flux-button-red mt-7">Download the complete 2026 Service Business Website Growth Report <ArrowUpRight size={16} /></Link></div></div><aside className="h-fit rounded-[2rem] border border-black/10 bg-white p-7 lg:sticky lg:top-28"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#DB3826]">Featured research</p><h2 className="mt-4 font-display text-2xl font-medium">2026 Website Growth Report</h2><p className="mt-4 text-sm leading-7 text-black/55">Explore our complete website growth research for clinics and service businesses.</p><Link href={reportHref} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#DB3826]">Read the report <ArrowUpRight size={15} /></Link></aside></article></section></main>;
}
