"use client";

import Link from "next/link";
import { m, useScroll, useTransform } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Check } from "@/components/ui/animated-icons";
import { useRef } from "react";
import PlatformEcosystem from "@/components/brand/PlatformEcosystem";

const layers = [
  ["01", "Patient Discovery Intelligence", "Before any of the rest of the system matters, patients need to find you and understand quickly whether you're the right fit.", "This layer covers your visibility in Google search results, your presence in AI search tools like ChatGPT and Perplexity when someone asks for a recommendation, your local map listing, and the content on your site that answers the specific questions a prospective patient is asking. A clinic can be excellent at patient care and still be invisible at this layer, simply because the digital presence wasn't built with this in mind."],
  ["02", "Patient Capture System", "Every channel a patient might use to reach you needs to feed into one place.", "A phone call, website form, chat message, or booking widget should never disappear into separate voicemail, email, and sticky notes. A capture system means every enquiry, regardless of channel, lands in one system that your team can see and act on."],
  ["03", "Patient Communication System", "Speed and consistency matter more than most clinics realize.", "A missed call answered with an automatic text within a minute keeps that patient engaged. A form submission that gets a reply the same day keeps that patient warm. The system automates responses that don't need judgment and flags the parts that do."],
  ["04", "Appointment Conversion System", "Interest that doesn't turn into a booked appointment is wasted interest.", "This layer covers how many steps booking takes, whether it works on a phone, whether reminders go out automatically to reduce no-shows, and whether scheduling connects directly to your calendar instead of requiring manual entry."],
  ["05", "Patient Continuity System", "The relationship doesn't end at the appointment.", "This layer covers review requests sent at the right moment, reactivation outreach for patients who haven't returned, and reminders for recurring care. It turns a single visit into a long-term patient relationship instead of a one-time transaction."],
];

const faqs = [
  ["What is a Patient Revenue System?", "A Patient Revenue System is a connected set of tools and workflows that carries a patient from first search through to becoming a returning patient, covering discovery, enquiry capture, communication, booking, and follow-up as one system instead of separate, disconnected tools."],
  ["How can clinics get more patient appointments?", "The fastest gains usually come from fixing the response gap rather than adding more traffic: responding to missed calls within a minute, replying to form submissions the same day, and following up automatically with patients who showed interest but didn't book."],
  ["Why do healthcare clinics lose leads?", "Most commonly because enquiries arrive through several channels—calls, forms, and chat—that aren't connected to one system, so some enquiries are missed entirely, and there's no consistent, fast follow-up for the ones that are caught."],
  ["How does AI help healthcare practices?", "Used well, AI can handle immediate, low-judgment tasks like responding to a missed call or drafting a follow-up message, freeing staff for the parts of patient communication that need a human. It works best inside an existing workflow, with a person reviewing anything that requires clinical or personal judgment."],
  ["What is the difference between healthcare marketing and a Patient Revenue System?", "Healthcare marketing focuses on generating traffic and leads. A Patient Revenue System covers the full journey after that lead arrives, including how quickly it's answered, how easily it converts into a booked appointment, and how the relationship continues after the visit."],
  ["How does appointment automation help clinics?", "Automated booking, reminders, and follow-up reduce the number of steps between interest and a confirmed appointment, and they reduce no-shows by keeping patients informed without relying on staff to manually track and remind each one."],
];

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <m.div initial={{ opacity: 0, y: 34 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .14 }} transition={{ delay, duration: .72, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</m.div>;
}

function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) {
  return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className={`flux-kicker ${light ? "text-flux" : "text-flux"}`}>{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.6rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>;
}

function FluidShapes() {
  return <div className="pointer-events-none absolute inset-0 overflow-hidden" aria-hidden="true">
    <m.div animate={{ x: [0, 70, -20, 0], y: [0, -35, 50, 0], rotate: [0, 18, -10, 0], borderRadius: ["42% 58% 65% 35%", "62% 38% 44% 56%", "36% 64% 55% 45%", "42% 58% 65% 35%"] }} transition={{ duration: 18, repeat: Infinity, ease: "easeInOut" }} className="absolute -right-28 top-24 h-[28rem] w-[28rem] bg-pulse opacity-35 blur-2xl" />
    <m.div animate={{ x: [0, -45, 35, 0], y: [0, 55, -20, 0], scale: [1, 1.12, .94, 1] }} transition={{ duration: 22, repeat: Infinity, ease: "easeInOut" }} className="absolute -left-32 bottom-0 h-80 w-80 rounded-full bg-flux/15 blur-3xl" />
  </div>;
}

export default function PatientRevenueSystemPage() {
  const journeyRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: journeyRef, offset: ["start end", "end start"] });
  const pathScale = useTransform(scrollYProgress, [0.12, .78], [0, 1]);

  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><FluidShapes /><div className="flux-shell relative z-10"><nav aria-label="Breadcrumb" className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><span>Patient Revenue System</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.2fr_.8fr] lg:items-end lg:py-16"><m.div initial={{ opacity: 0, y: 38 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8 }}><p className="flux-kicker mb-7 text-flux">Healthcare growth system</p><h1 className="max-w-6xl font-display text-[clamp(3.35rem,6vw,6.4rem)] font-medium leading-[.92] tracking-[-.07em]">The Patient Revenue System: Why getting more patients <span className="text-flux">isn&apos;t the real problem.</span></h1></m.div><m.div initial={{ opacity: 0, y: 26 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .14, duration: .7 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Most healthcare clinics don&apos;t have a demand problem. They have a connection problem. Patients search, call, and enquire every day, but the systems behind the front desk, website, and phone don&apos;t talk to each other.</p><p className="mt-5 text-lg leading-8 text-ink/65">A Patient Revenue System is how Flux connects the way patients discover you, reach you, book with you, and stay with you into a single system.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/business-intelligence-audit" className="flux-button flux-button-red">Get a free Patient Revenue Assessment <ArrowUpRight size={16} /></Link><a href="#five-layers" className="flux-button flux-button-line">See how the system works</a></div></m.div></div><a href="#hidden-problem" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">Follow the journey <span className="flex h-10 w-10 items-center justify-center rounded-full border border-ink/15 transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-500 group-hover:translate-y-1 group-hover:bg-ink group-hover:text-white"><ArrowDownRight size={16} /></span></a></div></section>

    <PlatformEcosystem variant="industry" />

    <section id="hidden-problem" className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="The hidden revenue problem">The bottleneck sits after attention.</Heading><div className="mt-14 grid gap-6 lg:grid-cols-[.62fr_.38fr]"><Reveal className="space-y-7 text-xl leading-9 text-ink/65"><p>Ask most clinic owners where their growth problem lives, and they&apos;ll point to marketing. More ads. More content. More reviews. More visibility.</p><p>That instinct isn&apos;t wrong, but it&apos;s incomplete. It assumes the bottleneck is attention. For most clinics, it isn&apos;t. The bottleneck sits in the gap between a patient showing interest and a patient sitting in a chair.</p><p>A patient calls during a busy hour and nobody picks up. A form arrives at 9pm and sits unread. A chat question receives a reply the next business day. A patient doesn&apos;t show up and nobody follows up to rebook them.</p><p>None of this appears in a Google Ads dashboard. It appears as a slow month and gets blamed on demand, when the demand was there all along.</p></Reveal><Reveal delay={.1} className="flex min-h-[430px] flex-col justify-between rounded-[2rem] bg-flux p-8 text-white md:p-10"><p className="flux-kicker text-white/60">Not a marketing failure</p><p className="font-display text-4xl font-medium leading-tight">It&apos;s an operating problem. The website, phone, calendar, follow-up, and people are working in isolation.</p><p className="text-sm leading-7 text-white/65">That connected system is what we call a Patient Revenue System.</p></Reveal></div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="What it is">One process, with visibility from first search to returning patient.</Heading><div className="mt-14 grid gap-8 lg:grid-cols-2"><Reveal className="rounded-[2rem] bg-white p-8 md:p-12"><p className="text-xl leading-9 text-ink/68">A Patient Revenue System is the connected set of tools and workflows that carries a patient from the moment they search for care to the moment they become a returning patient, without losing them at any step along the way.</p><p className="mt-7 text-xl leading-9 text-ink/68">It is built from five layers that work together: discovery, capture, communication, conversion, and continuity.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-ink p-8 text-white md:p-12"><p className="text-xl leading-9 text-white/65">Patient acquisition rarely happens in a straight line. Search, website, phone, CRM, reviews, and booking are usually owned by different systems. When they are disconnected, nobody sees the full journey and gaps between systems become gaps in revenue.</p><p className="mt-8 font-display text-3xl font-medium">A missed call costs more than one appointment—it costs potential repeat visits and referrals.</p></Reveal></div></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Why marketing is not enough" light>Replace traffic, leads, and hope with a connected relationship.</Heading><div className="mt-14 grid gap-5 lg:grid-cols-2"><Reveal className="rounded-[2rem] border border-white/20 p-8 md:p-12"><p className="flux-kicker text-white/40">Traditional model</p><p className="mt-12 font-display text-5xl font-medium">Traffic.<br />Leads.<br /><span className="text-white/30">Hope.</span></p><p className="mt-10 text-base leading-8 text-white/55">The marketing company&apos;s job ends at the lead. What happens next becomes the clinic&apos;s problem, with little visibility into where those leads go cold.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-flux p-8 md:p-12"><p className="flux-kicker text-white/60">Connected model</p><p className="mt-12 font-display text-5xl font-medium">Discovery.<br />Conversation.<br />Appointment.<br />Relationship.</p><p className="mt-10 text-base leading-8 text-white/70">The patient is supported from discovery to booking and beyond through reminders, reviews, and reactivation.</p></Reveal></div><p className="mt-12 max-w-4xl text-xl leading-9 text-white/60">Traditional marketing concentrates on the top of the funnel. A Patient Revenue System puts equal energy into what happens after someone raises their hand—where most preventable revenue loss occurs.</p></div></section>

    <section id="five-layers" ref={journeyRef} className="relative overflow-hidden bg-cream py-24 md:py-36"><FluidShapes /><div className="flux-shell relative z-10"><Heading eyebrow="The five layers">Each layer works alone. The value comes from connecting all five.</Heading><div className="relative mt-16"><div className="absolute bottom-0 left-[19px] top-0 w-px bg-ink/15 md:left-1/2" /><m.div style={{ scaleY: pathScale, transformOrigin: "top" }} className="absolute bottom-0 left-[19px] top-0 w-px bg-flux md:left-1/2" />{layers.map(([number, title, lead, body], index) => <Reveal key={title} className={`relative mb-8 grid gap-5 pl-14 md:grid-cols-2 md:pl-0 ${index % 2 ? "" : ""}`}><span className="absolute left-0 top-8 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-flux text-xs font-bold text-white md:left-1/2 md:-translate-x-1/2">{number}</span><article className={`rounded-[2rem] border border-ink/10 bg-white p-7 shadow-[0_20px_70px_rgba(6,7,10,.06)] md:p-10 ${index % 2 ? "md:col-start-2 md:ml-12" : "md:mr-12"}`}><h3 className="font-display text-3xl font-medium md:text-4xl">{title}</h3><p className="mt-6 text-lg font-semibold leading-8">{lead}</p><p className="mt-5 text-base leading-8 text-ink/60">{body}</p></article></Reveal>)}</div></div></section>

    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="How Flux builds it">Visibility first. Connection second. Continuous improvement after launch.</Heading><div className="mt-14 grid gap-12 lg:grid-cols-[.58fr_.42fr]"><Reveal className="space-y-7 text-xl leading-9 text-ink/65"><p>Flux is an operating intelligence company. For healthcare, that means we don&apos;t sell websites, SEO, or automation as separate services. We build the connected system underneath all three.</p><p>Before building anything, we examine how enquiries move through your clinic and identify where they are lost: missed calls, slow form responses, booking friction, or follow-up that only exists in someone&apos;s memory.</p><p>Then we connect the website, automated response, booking calendar, and follow-up. Where AI genuinely helps, we use it. Where judgment is needed, the system routes the task to a person.</p><p>The result is a system your team can see into. Instead of guessing why a month was slow, you can see exactly which stage needs attention.</p></Reveal><div className="space-y-3">{["Patient journey assessment", "Connected system blueprint", "Website, response, booking, and follow-up build", "Real enquiry scenario testing", "Ongoing visibility and improvement"].map((item, index) => <Reveal key={item} delay={index * .05} className="flex items-center gap-4 rounded-2xl bg-cream p-6"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-flux text-white"><Check size={15} /></span><p className="font-display text-xl font-medium">{item}</p></Reveal>)}</div></div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Who it is built for">Healthcare businesses where every missed enquiry has a real cost.</Heading><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{["Dental clinics", "Physiotherapy & chiropractic", "Pain management practices", "Med spas & wellness clinics", "Specialty practices"].map((item, index) => <Reveal key={item} delay={index * .05} className="flex min-h-[230px] flex-col justify-between rounded-[1.75rem] bg-white p-7 transition-transform duration-500 hover:-translate-y-2"><span className="text-xs font-bold text-flux">0{index + 1}</span><h3 className="font-display text-2xl font-medium">{item}</h3></Reveal>)}</div><p className="mt-10 max-w-4xl text-lg leading-8 text-ink/65">Built for clinics with 3 to 50 staff, an existing website, and steady enquiries that are not converting as well as they should. It is not built for practices that do not take enquiries through phone, form, or online booking.</p></div></section>

    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="System comparison">The lead is the beginning of the work—not the end.</Heading><div className="mt-14 overflow-hidden rounded-[2rem] border border-ink/15"><div className="grid md:grid-cols-2"><Reveal className="p-8 md:p-12"><p className="flux-kicker text-ink/40">Traditional healthcare marketing</p><p className="mt-9 text-xl leading-9 text-ink/65">Focuses on traffic and leads. Success is measured by clicks, impressions, and lead volume. What happens after the lead is the clinic&apos;s responsibility.</p></Reveal><Reveal delay={.08} className="bg-ink p-8 text-white md:p-12"><p className="flux-kicker text-flux">Patient Revenue System</p><p className="mt-9 text-xl leading-9 text-white/65">Focuses on the full journey from first search to long-term relationship. Success is measured by enquiries becoming appointments and appointments becoming returning patients.</p></Reveal></div></div></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Related healthcare systems" light>Continue through the connected system.</Heading><div className="mt-14 grid border-t border-white/20 md:grid-cols-2 lg:grid-cols-5">{[["Patient Revenue System for Clinics", "/clinics"], ["Healthcare Implementation", "/industries/healthcare"], ["Clinic Booking Automation", "/services/clinic-appointment-booking-automation"], ["Operating Intelligence", "/operating-intelligence"], ["Business Intelligence Audit", "/business-intelligence-audit"]].map(([title, href]) => <Link key={href} href={href} className="group flex min-h-[240px] flex-col justify-between border-b border-white/20 p-7 transition-colors duration-500 hover:bg-white hover:text-ink md:border-r"><ArrowUpRight className="ml-auto transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /><h3 className="font-display text-2xl font-medium">{title}</h3></Link>)}</div></div></section>

    <section className="bg-cream py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="FAQ">Questions about Patient Revenue Systems.</Heading><div className="mt-14 divide-y divide-ink/15 border-y border-ink/15">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-ink/15 transition-transform duration-500 group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>

    <section className="relative overflow-hidden bg-flux py-24 text-white md:py-36"><m.div animate={{ rotate: 360 }} transition={{ duration: 36, repeat: Infinity, ease: "linear" }} className="absolute -right-40 -top-40 h-[34rem] w-[34rem] rounded-[42%_58%_66%_34%] border border-white/20" /><div className="flux-shell relative z-10"><p className="flux-kicker text-white/60">Free Patient Revenue Assessment</p><Reveal><h2 className="mt-7 max-w-6xl font-display text-[clamp(3rem,5.5vw,5.7rem)] font-medium leading-[.95] tracking-[-.06em]">See exactly where your clinic is losing patient opportunities.</h2></Reveal><p className="mt-9 max-w-3xl text-xl leading-9 text-white/70">We&apos;ll show you where opportunities are being lost before you spend another dollar on marketing. No obligation, and we respond within 24 hours.</p><Link href="/business-intelligence-audit" className="flux-button mt-10 bg-white text-ink">Get your free assessment <ArrowUpRight size={16} /></Link></div></section>
  </>;
}
