"use client";
import Link from "next/link";
import { m } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Ban, BrainCircuit, Link2, Sparkles, Users, Workflow } from "@/components/ui/animated-icons";

const principles = [
  ["01", "Connection creates intelligence", "A disconnected business sees pieces. A connected business sees the whole picture.", "Before adding or automating, Flux connects the perspectives already inside the business. Intelligence is not another product. It emerges when information that already exists can finally talk to itself.", Link2],
  ["02", "Intelligence before automation", "Automating a process before understanding it makes a flawed process happen faster.", "We ask what the business must understand first. Once that visibility exists, automation becomes a force multiplier instead of a faster version of the same guesswork.", BrainCircuit],
  ["03", "Customers are the center", "Customers experience one continuous relationship—not your internal departments.", "Systems should follow Discovery → Conversation → Decision → Relationship. Organizing around that journey optimizes the experience that produces a long-term customer.", Users],
  ["04", "AI is a capability, not a strategy", "An AI tool bolted onto a disconnected business makes disconnected decisions faster.", "AI becomes valuable when connected to real business knowledge, customer context, and operations. It should handle defined tasks while people retain the judgment calls.", Sparkles],
  ["05", "Build for the future", "A solution for today's problem is a project. A system that keeps improving is a foundation.", "Flux builds systems that become more useful as information flows through them and adapt as the business changes instead of requiring another rebuild.", Workflow],
];
const faqs = [
  ["What is Flux?", "Flux is an Operating Intelligence Company. We build connected systems that help service businesses discover customers, understand where revenue is won or lost, move customers through their journey, and use automation and AI where they genuinely help."],
  ["Why is Flux different from a digital agency?", "Most agencies focus on individual activities: a website, campaign, or CRM setup. Flux focuses on the operating system underneath—the connections that determine whether those activities actually produce growth."],
  ["What does Operating Intelligence mean?", "Operating Intelligence is the ability to connect data, customer interactions, systems, workflows, and AI capabilities to make better decisions, operate efficiently, and continuously improve growth."],
  ["Why do businesses need intelligent systems?", "Most businesses already have enough tools. They lack the connection that reveals where opportunities are won or lost."],
  ["How does Flux help businesses evolve?", "By understanding before automating, connecting existing systems before adding new ones, and building visibility a team can act on immediately."],
  ["What does Flux believe about AI?", "AI is a capability, not a strategy. It becomes useful when connected to real knowledge and operational systems, handling well-defined tasks while people own judgment."],
];
function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) { return <m.div initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .14 }} transition={{ delay, duration: .7, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</m.div>; }
function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) { return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className="flux-kicker text-flux">{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.6rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>; }

export default function PhilosophyPage() {
  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><m.div animate={{ x: [0, 60, -25, 0], y: [0, -40, 35, 0], borderRadius: ["42% 58% 65% 35%", "64% 36% 45% 55%", "37% 63% 56% 44%", "42% 58% 65% 35%"] }} transition={{ duration: 20, repeat: Infinity }} className="pointer-events-none absolute -right-32 top-24 h-[31rem] w-[31rem] bg-pulse opacity-40 blur-2xl" /><div className="flux-shell relative z-10"><nav className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><span>Why Flux</span><span className="mx-2">/</span><span>Our Philosophy</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.18fr_.82fr] lg:items-end lg:py-16"><m.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }}><p className="flux-kicker mb-7 text-flux">Our Philosophy</p><h1 className="font-display text-[clamp(3.45rem,6.25vw,6.6rem)] font-medium leading-[.91] tracking-[-.07em]">The future belongs to <span className="text-flux">intelligent businesses.</span></h1></m.div><m.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Technology changed how businesses operate. It did not automatically make growth clearer. Flux exists because the businesses that win will not own the most tools—their systems will understand customers, connect, and improve over time.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/operating-intelligence" className="flux-button flux-button-red">Explore Operating Intelligence <ArrowUpRight size={16} /></Link><Link href="/business-intelligence-audit" className="flux-button flux-button-line">Measure your score</Link></div></m.div></div><a href="#world-changed" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">Why Flux exists <ArrowDownRight size={16} /></a></div></section>

    <section id="world-changed" className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="The world changed">Business systems did not.</Heading><div className="mt-14 grid gap-10 lg:grid-cols-[.62fr_.38fr]"><Reveal className="space-y-7 text-xl leading-9 text-ink/65"><p>Over two decades, businesses adopted websites, CRMs, marketing platforms, analytics, automation, and now AI assistants.</p><p>Each addition solved an urgent problem. Nobody designed how all the pieces should work together because companies bought tools one at a time—not a system.</p><p>The result looks impressive outside and functions as separate rooms inside. Marketing, sales, and operations each see a different customer, while that customer experiences one relationship and notices when it feels fragmented.</p><p>Complexity increased faster than connection. That gap between more tools and more clarity is the problem Flux exists to close.</p></Reveal><Reveal delay={.08} className="flex min-h-[420px] flex-col justify-between rounded-[2rem] bg-ink p-8 text-white"><p className="flux-kicker text-white/45">The central belief</p><p className="font-display text-4xl font-medium">More technology does not create intelligence.<br /><span className="text-flux">Connection does.</span></p></Reveal></div></div></section>

    <section className="bg-cream py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Five principles">The beliefs behind every system Flux builds.</Heading><div className="mt-16 space-y-5">{principles.map(([number, title, lead, body, Icon], index) => { const PrincipleIcon = Icon; return <Reveal key={title as string} delay={index * .04} className={`grid gap-8 rounded-[2rem] p-8 md:grid-cols-[5rem_.42fr_.58fr] md:p-11 ${index === 1 ? "bg-pulse-light" : index === 3 ? "bg-ink text-white" : index === 4 ? "bg-flux text-white" : "bg-white"}`}><div className="flex items-start justify-between md:block"><span className="text-xs font-bold opacity-45">{number as string}</span><PrincipleIcon className="mt-0 md:mt-12" /></div><div><h3 className="font-display text-3xl font-medium md:text-4xl">{title as string}</h3><p className="mt-5 text-lg font-semibold leading-8">{lead as string}</p></div><p className="text-base leading-8 opacity-60">{body as string}</p></Reveal>; })}</div></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="What we reject" light>An approach is also defined by what it refuses to do.</Heading><div className="mt-14 grid gap-4 md:grid-cols-2">{[["More tools without purpose", "Technology should solve a specific, understood gap—not add complexity because it is available."], ["Marketing without intelligence", "Traffic and leads are inputs. Without visibility into what follows, they are numbers rather than growth."], ["Automation without understanding", "A process should be understood and improved before it is automated."], ["Short-term tactics", "Campaigns expire. Flux builds systems intended to work and improve years from now."]].map(([title, body], index) => <Reveal key={title} delay={index * .05} className="flex min-h-[280px] flex-col justify-between rounded-[2rem] border border-white/20 p-8 transition-colors duration-500 hover:bg-white hover:text-ink"><Ban className="text-flux" /><div><h3 className="font-display text-3xl font-medium">{title}</h3><p className="mt-5 text-sm leading-7 opacity-60">{body}</p></div></Reveal>)}</div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="The Flux approach">Understand. Connect. Build intelligence. Improve.</Heading><div className="mt-14 grid gap-3 md:grid-cols-4">{[["01", "Understand", "Learn how the business operates, how customers move, and where real gaps exist."], ["02", "Connect", "Let existing systems share information rather than holding separate versions of the customer."], ["03", "Intelligence", "Create visibility into where opportunity is won, stalled, or lost."], ["04", "Improve", "Keep evolving the system as the business and its customers change."]].map(([number, title, body], index) => <Reveal key={title} delay={index * .06} className={`flex min-h-[320px] flex-col justify-between rounded-[1.75rem] p-7 ${index === 2 ? "bg-flux text-white" : "bg-white"}`}><span className="text-xs font-bold opacity-45">{number}</span><div><h3 className="font-display text-3xl font-medium">{title}</h3><p className="mt-5 text-sm leading-7 opacity-60">{body}</p></div></Reveal>)}</div><div className="mt-10 flex flex-wrap gap-3"><Link href="/the-problem" className="flux-button flux-button-line">See the operating problem</Link><Link href="/methodology" className="flux-button flux-button-line">Explore the methodology</Link></div></div></section>

    <section className="relative overflow-hidden bg-flux py-24 text-white md:py-40"><m.div animate={{ rotate: 360 }} transition={{ duration: 40, repeat: Infinity, ease: "linear" }} className="absolute -right-52 -top-52 h-[42rem] w-[42rem] rounded-[38%_62%_57%_43%] border border-white/20" /><div className="flux-shell relative z-10"><p className="flux-kicker text-white/55">The future we are building</p><Reveal><h2 className="mt-7 max-w-6xl font-display text-[clamp(3rem,5.8vw,6rem)] font-medium leading-[.95] tracking-[-.06em]">The next decade belongs to businesses that learn fastest, respond fastest, and understand customers most clearly.</h2></Reveal><p className="mt-10 max-w-3xl text-xl leading-9 text-white/70">Flux is building the connected Operating Intelligence that lets service businesses compete on understanding and speed—not only on how much they spend generating attention.</p></div></section>

    <section className="bg-cream py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="FAQ">Questions about Flux and its philosophy.</Heading><div className="mt-14 divide-y divide-ink/15 border-y border-ink/15">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 items-center justify-center rounded-full border border-ink/15 transition-transform group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Put the philosophy to work" light>Explore the systems—or measure where your business stands today.</Heading><div className="mt-12 flex flex-wrap gap-4"><Link href="/operating-intelligence" className="flux-button bg-white text-ink">Explore Operating Intelligence <ArrowUpRight size={16} /></Link><Link href="/business-intelligence-audit" className="flux-button border border-white/30 text-white">Measure your score</Link><Link href="/about" className="flux-button border border-white/30 text-white">About Flux</Link></div></div></section>
  </>;
}
