"use client";

import Link from "next/link";
import { m, useScroll, useTransform } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Check, Database, MessageSquare, Phone, Radio, Workflow } from "lucide-react";
import { useRef } from "react";
import PlatformEcosystem from "@/components/brand/PlatformEcosystem";

const leaks = [
  ["Discovery", "Budget is allocated by assumption because nobody knows which channels actually produce customers."],
  ["Capture", "Calls, forms, and chats arrive in separate places, and some are never logged where the team can see them."],
  ["Response", "A lead waits for hours or days because ownership is unclear or nobody knows a follow-up is due."],
  ["Sales conversations", "The person on the call cannot see what the prospect viewed or asked before, so every conversation starts at zero."],
  ["Follow-up", "Deals that do not close immediately disappear because no system tracks the next touch."],
  ["Retention", "Existing customers receive no further attention because new-business and relationship data remain separate."],
];

const framework = [
  ["01", "Signal Collection", "Every website visit, call, form, message, and CRM update generates a signal. The first step captures all of them in one place instead of leaving them scattered across systems."],
  ["02", "Customer Journey Visibility", "Signals are connected into a sequence: where a customer came from, what they asked, how long they waited, and whether they converted. Events become a journey a team can understand."],
  ["03", "Opportunity Intelligence", "Connected journeys reveal which channels produce high-value customers, where opportunities disappear, and which active leads match the business's best-converting patterns."],
  ["04", "Decision Intelligence", "Findings become direction: where to put the next marketing dollar, which sales step needs attention, and what to fix before generating more leads through the same gaps."],
];

const buildSteps = [
  ["Discovery", "We examine the CRM, website, communication tools, and the data that exists but is not connected."],
  ["System design", "We map how signals should connect around the way the business actually operates."],
  ["Connection", "We build integrations and workflows so the journey view updates automatically."],
  ["Implementation", "We surface findings in a form the team can use immediately, without a data analyst."],
  ["Continuous improvement", "We adjust the system as the business changes so its intelligence remains trusted."],
];

const faqs = [
  ["What is Revenue Intelligence?", "Revenue Intelligence is the practice of connecting a business's marketing, sales, communication, and CRM data into one understood view of where opportunities come from, how they move, and where they're being lost."],
  ["How is Revenue Intelligence different from CRM?", "A CRM stores contact records and logs activity. Revenue Intelligence connects that data with marketing and communication signals to show the full customer journey and surface where opportunities are actually being lost, not just what activity took place."],
  ["Why do businesses need Revenue Intelligence?", "Because most businesses collect data across several disconnected systems, which makes it difficult to know with confidence where growth is coming from or where it is being lost. Revenue Intelligence connects those systems so decisions can be based on evidence instead of guesswork."],
  ["How can Revenue Intelligence improve revenue?", "By identifying specific points where opportunities are lost, such as slow response times or under-tracked channels, so a business can fix the exact gap causing lost revenue rather than spending more on generating new leads that leak through the same gap."],
  ["Can AI improve revenue operations?", "Yes, when it's used to handle well-defined, repeatable tasks like flagging a stalled lead or summarizing a customer's journey so far. It works best as part of a connected system with human oversight, not as a replacement for judgment."],
  ["What data does Revenue Intelligence use?", "Website behavior, call logs, form submissions, chat and message history, and CRM activity, connected together rather than reviewed separately."],
];

const signalNodes = [
  { Icon: Database, x: "12%", y: "28%" },
  { Icon: Phone, x: "76%", y: "18%" },
  { Icon: MessageSquare, x: "82%", y: "72%" },
  { Icon: Workflow, x: "20%", y: "76%" },
];

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <m.div initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .14 }} transition={{ delay, duration: .7, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</m.div>;
}

function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) {
  return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className="flux-kicker text-flux">{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.6rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>;
}

function SignalField() {
  return <div className="relative min-h-[410px] overflow-hidden rounded-[2rem] bg-ink text-white">
    <m.div animate={{ rotate: 360 }} transition={{ duration: 30, repeat: Infinity, ease: "linear" }} className="absolute left-1/2 top-1/2 h-72 w-72 -translate-x-1/2 -translate-y-1/2 rounded-[42%_58%_62%_38%] border border-white/15" />
    <m.div animate={{ rotate: -360 }} transition={{ duration: 24, repeat: Infinity, ease: "linear" }} className="absolute left-1/2 top-1/2 h-52 w-52 -translate-x-1/2 -translate-y-1/2 rounded-[62%_38%_44%_56%] bg-flux/85 blur-[1px]" />
    {signalNodes.map(({ Icon, x, y }, index) => <m.span key={`${x}-${y}`} style={{ left: x, top: y }} animate={{ y: [0, -10, 0], scale: [1, 1.07, 1] }} transition={{ duration: 3.6 + index, repeat: Infinity, ease: "easeInOut" }} className="absolute z-10 flex h-14 w-14 items-center justify-center rounded-full border border-white/20 bg-white/10 backdrop-blur"><Icon size={20} /></m.span>)}
    <div className="absolute inset-0 flex items-center justify-center"><div className="z-10 text-center"><Radio className="mx-auto mb-3" /><p className="flux-kicker text-white">One connected view</p></div></div>
  </div>;
}

export default function RevenueIntelligencePage() {
  const frameworkRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: frameworkRef, offset: ["start end", "end start"] });
  const lineScale = useTransform(scrollYProgress, [.12, .8], [0, 1]);

  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><m.div animate={{ x: [0, 70, -30, 0], y: [0, -40, 30, 0], borderRadius: ["45% 55% 64% 36%", "63% 37% 42% 58%", "38% 62% 55% 45%", "45% 55% 64% 36%"] }} transition={{ duration: 20, repeat: Infinity, ease: "easeInOut" }} className="pointer-events-none absolute -right-32 top-24 h-[30rem] w-[30rem] bg-pulse opacity-40 blur-2xl" /><div className="flux-shell relative z-10"><nav aria-label="Breadcrumb" className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><span>Revenue Intelligence</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.18fr_.82fr] lg:items-end lg:py-16"><m.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .82 }}><p className="flux-kicker mb-7 text-flux">Revenue Intelligence</p><h1 className="max-w-6xl font-display text-[clamp(3.4rem,6.2vw,6.5rem)] font-medium leading-[.91] tracking-[-.07em]">Turn disconnected business data into <span className="text-flux">Revenue Intelligence.</span></h1></m.div><m.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15, duration: .72 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Most businesses don&apos;t have a data problem. They have data everywhere: a CRM, website, call logs, forms, emails, and spreadsheets. What they lack is a way to see how those pieces connect.</p><p className="mt-5 text-lg leading-8 text-ink/65">Revenue Intelligence connects those signals into something a business can actually act on.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/business-intelligence-audit" className="flux-button flux-button-red">Get a free Revenue Intelligence Assessment <ArrowUpRight size={16} /></Link><a href="#framework" className="flux-button flux-button-line">See how the framework works</a></div></m.div></div><a href="#hidden-problem" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">Follow the signals <span className="flex h-10 w-10 items-center justify-center rounded-full border border-ink/15 transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-500 group-hover:translate-y-1 group-hover:bg-ink group-hover:text-white"><ArrowDownRight size={16} /></span></a></div></section>

    <PlatformEcosystem variant="intelligence" />

    <section id="hidden-problem" className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="The hidden growth problem">Each system tells a partial story. None tells the whole one.</Heading><div className="mt-14 grid gap-10 lg:grid-cols-[.55fr_.45fr]"><Reveal className="space-y-7 text-xl leading-9 text-ink/65"><p>Most growing service businesses have already invested in the obvious things: a CRM, marketing budget, analytics, and automation. Yet growth still feels harder than it should, and nobody can say exactly why.</p><p>The tools don&apos;t talk to each other. Marketing knows how many leads arrived, but not which became customers. Sales knows which deals closed, but not which channel or page produced them. The CRM records calls and emails, but not what happened before the customer picked up the phone.</p><p>When leadership decides what to fix, the answer is often a guess dressed up as a decision because the evidence is scattered across five logins never designed to be read together.</p><p>Revenue Intelligence closes this gap—not by adding another dashboard, but by connecting what is already collected so it can be understood.</p></Reveal><SignalField /></div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="What it is">Connected customer and revenue data, understood as one journey.</Heading><div className="mt-14 grid gap-6 lg:grid-cols-2"><Reveal className="rounded-[2rem] bg-white p-8 md:p-12"><p className="text-xl leading-9 text-ink/68">Revenue Intelligence connects a business&apos;s customer and revenue data across marketing, sales, communication, and CRM systems into a single view of where opportunities come from, how they move, and where they are lost.</p><p className="mt-7 text-xl leading-9 text-ink/68">It is needed wherever customers move through multiple channels before becoming a paying client: a website visit, call, form, conversation, and follow-up.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-ink p-8 text-white md:p-12"><p className="text-xl leading-9 text-white/65">Predictable businesses are not those with the most data. They can quickly answer which channel produced their best customers, where interested people go quiet, and what changed when conversions dropped.</p><p className="mt-8 font-display text-3xl font-medium">Connected signals turn those questions from a manual investigation into answers available in minutes.</p></Reveal></div><p className="mt-12 max-w-5xl text-xl leading-9 text-ink/65">In practice, website behavior, calls, forms, messages, and CRM activity are mapped against the real customer journey and surfaced as actionable findings rather than raw numbers a team must interpret alone.</p></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Data vs reporting vs intelligence" light>Collected information only becomes valuable when it changes a decision.</Heading><div className="mt-14 grid gap-4 lg:grid-cols-3">{[["Data", "Information collected", "A form submission. A call log. A CRM entry. Most businesses have plenty of it sitting in systems that do not connect."], ["Reporting", "Information organized", "Dashboards show what happened but rarely explain why. Marketing and sales reports often disagree because each is built one system at a time."], ["Intelligence", "Information used to decide", "Not just 40 leads—but which sources produced the best ones, how long they took to convert, and precisely where the rest dropped off."]].map(([title, lead, body], index) => <Reveal key={title} delay={index * .07} className={`flex min-h-[360px] flex-col justify-between rounded-[2rem] p-8 ${index === 2 ? "bg-flux" : "border border-white/20"}`}><span className="text-xs font-bold opacity-40">0{index + 1}</span><div><h3 className="font-display text-4xl font-medium">{title}</h3><p className="mt-4 text-lg font-semibold">{lead}</p><p className="mt-5 text-sm leading-7 opacity-60">{body}</p></div></Reveal>)}</div></div></section>

    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Where opportunities are lost">Small gaps compound across the full customer journey.</Heading><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{leaks.map(([title, body], index) => <Reveal key={title} delay={index * .05} className={`group flex min-h-[290px] flex-col justify-between rounded-[1.75rem] p-7 transition-[transform,border-radius] duration-500 hover:-translate-y-2 hover:rounded-[2.2rem] ${index === 0 ? "bg-flux text-white" : index === 3 ? "bg-pulse-light" : "bg-cream"}`}><div className="flex justify-between"><span className="text-xs font-bold opacity-45">0{index + 1}</span><ArrowUpRight className="transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /></div><div><h3 className="font-display text-3xl font-medium">{title}</h3><p className="mt-5 text-sm leading-7 opacity-65">{body}</p></div></Reveal>)}</div><p className="mt-10 max-w-4xl text-xl leading-9 text-ink/65">Together, these gaps usually represent more lost revenue across a year than any single marketing campaign could recover.</p></div></section>

    <section id="framework" ref={frameworkRef} className="relative overflow-hidden bg-cream py-24 md:py-36"><div className="pointer-events-none absolute -left-48 top-1/3 h-96 w-96 rounded-full bg-pulse/35 blur-3xl" /><div className="flux-shell relative z-10"><Heading eyebrow="The Flux framework">From scattered signals to clear decisions.</Heading><div className="relative mt-16"><div className="absolute bottom-0 left-[19px] top-0 w-px bg-ink/15 md:left-1/2" /><m.div style={{ scaleY: lineScale, transformOrigin: "top" }} className="absolute bottom-0 left-[19px] top-0 w-px bg-flux md:left-1/2" />{framework.map(([number, title, body], index) => <Reveal key={title} className="relative mb-8 grid gap-6 pl-14 md:grid-cols-2 md:pl-0"><span className="absolute left-0 top-8 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-flux text-xs font-bold text-white md:left-1/2 md:-translate-x-1/2">{number}</span><article className={`rounded-[2rem] border border-ink/10 bg-white p-8 shadow-[0_20px_70px_rgba(6,7,10,.06)] md:p-11 ${index % 2 ? "md:col-start-2 md:ml-12" : "md:mr-12"}`}><h3 className="font-display text-3xl font-medium md:text-4xl">{title}</h3><p className="mt-6 text-base leading-8 text-ink/60">{body}</p></article></Reveal>)}</div></div></section>

    <section className="bg-flux py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Powered by Operating Intelligence" light>Intelligence shows where growth is blocked. The operating system acts on it.</Heading><div className="mt-14 grid gap-10 border-t border-white/25 pt-8 lg:grid-cols-[.62fr_.38fr]"><Reveal className="space-y-7 text-xl leading-9 text-white/70"><p>Revenue Intelligence is one layer of Operating Intelligence: connected systems that help a service business discover customers, capture opportunities, communicate effectively, and understand what drives or blocks growth.</p><p>It reveals where opportunities are lost. The broader operating system acts on those answers by fixing response gaps, rebuilding booking flows, or connecting previously invisible channels.</p></Reveal><Link href="/operating-intelligence" className="group flex min-h-[230px] flex-col justify-between rounded-[2rem] bg-white p-8 text-ink transition-transform duration-500 hover:-translate-y-2"><ArrowUpRight className="ml-auto transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /><p className="font-display text-3xl font-medium">Explore Operating Intelligence</p></Link></div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="For service businesses">Different industries. The same visibility gap.</Heading><div className="mt-14 grid gap-4 md:grid-cols-2">{[["Healthcare", "Clinics need visibility into where patient enquiries are lost across calls, booking, and follow-up—not only how many ads were clicked.", "/industries/healthcare"], ["Home services", "Contractors need to see which quote sources produce jobs that close, not simply which produce the most calls.", "/industries/home-services"], ["Professional services", "Longer sales cycles require visibility into which touchpoints move a prospect and which conversations stall.", "/industries/legal"], ["Appointment-based businesses", "Where a missed response means a missed booking, the full path from contact to appointment must be visible.", "/customer-progression"]].map(([title, body, href], index) => <Reveal key={title} delay={index * .05}><Link href={href} className="group flex min-h-[270px] flex-col justify-between rounded-[2rem] bg-white p-8 transition-transform duration-500 hover:-translate-y-2"><ArrowUpRight className="ml-auto text-flux transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /><div><h3 className="font-display text-3xl font-medium">{title}</h3><p className="mt-5 max-w-xl text-sm leading-7 text-ink/60">{body}</p></div></Link></Reveal>)}</div></div></section>

    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Revenue Intelligence vs CRM">A CRM is necessary. It is rarely the whole picture.</Heading><div className="mt-14 grid overflow-hidden rounded-[2rem] border border-ink/15 md:grid-cols-2"><Reveal className="p-8 md:p-12"><p className="flux-kicker text-ink/40">Traditional CRM</p><p className="mt-10 text-xl leading-9 text-ink/65">Stores contact records and logs calls and emails. It requires manual entry and interpretation, showing what the sales team did rather than what caused a customer to convert or disappear.</p></Reveal><Reveal delay={.08} className="bg-ink p-8 text-white md:p-12"><p className="flux-kicker text-flux">Flux Revenue Intelligence</p><p className="mt-10 text-xl leading-9 text-white/65">Connects marketing, communication, and CRM data into one journey view. It surfaces where opportunities are lost and turns scattered records into findings a team can act on this week.</p></Reveal></div></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="How Flux builds it" light>A system designed around how your business actually operates.</Heading><div className="mt-14 divide-y divide-white/20 border-y border-white/20">{buildSteps.map(([title, body], index) => <Reveal key={title} delay={index * .04} className="group grid gap-5 py-8 md:grid-cols-[4rem_.35fr_.65fr]"><span className="text-xs font-bold text-flux">0{index + 1}</span><h3 className="font-display text-2xl font-medium transition-transform duration-500 group-hover:translate-x-2 md:text-3xl">{title}</h3><p className="text-base leading-8 text-white/55">{body}</p></Reveal>)}</div></div></section>

    <section className="bg-cream py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="FAQ">Questions about connected revenue intelligence.</Heading><div className="mt-14 divide-y divide-ink/15 border-y border-ink/15">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-ink/15 transition-transform duration-500 group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>

    <section className="relative overflow-hidden bg-flux py-24 text-white md:py-36"><m.div animate={{ rotate: 360 }} transition={{ duration: 38, repeat: Infinity, ease: "linear" }} className="absolute -right-48 -top-48 h-[38rem] w-[38rem] rounded-[38%_62%_58%_42%] border border-white/20" /><div className="flux-shell relative z-10"><p className="flux-kicker text-white/60">Business Intelligence Assessment</p><Reveal><h2 className="mt-7 max-w-6xl font-display text-[clamp(3rem,5.5vw,5.7rem)] font-medium leading-[.95] tracking-[-.06em]">Find the gaps between acquisition, follow-up, and revenue data.</h2></Reveal><p className="mt-9 max-w-3xl text-xl leading-9 text-white/70">Review where the current system loses visibility or ownership before adding more demand to the same journey.</p><Link href="/business-intelligence-audit" className="flux-button mt-10 bg-white text-ink">Start your assessment <ArrowUpRight size={16} /></Link></div></section>
  </>;
}
