"use client";

import Link from "next/link";
import { m } from "framer-motion";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import PlatformEcosystem from "@/components/brand/PlatformEcosystem";

const framework = [
  ["01", "Patient Discovery Intelligence", "Helping healthcare businesses become visible where patients are actually looking: traditional search, AI tools like ChatGPT and Google AI Overviews, local maps, reviews, and mentions across the web.", "/ai-discovery"],
  ["02", "Patient Revenue Systems", "Turning patient interest into booked appointments through connected enquiry capture, fast communication, simple booking, and consistent follow-up.", "/patient-revenue-system"],
  ["03", "Revenue Intelligence", "Understanding where patient opportunities come from, where they convert, and where they are lost by connecting data across marketing, front desk, and practice systems.", "/revenue-intelligence"],
  ["04", "Customer Progression", "Improving how patients move from initial enquiry through appointment, ongoing care, and retention rather than treating every visit as a disconnected event.", "/customer-progression"],
  ["05", "AI Healthcare Systems", "Using AI where it genuinely helps—instant missed-call response, follow-up drafting, and enquiry summaries—with people available for judgment calls.", "/ai-discovery"],
];

const challenges = [
  ["Patient acquisition", "Clinics struggle to consistently attract qualified patients through the channels that matter now.", "Build visibility across traditional and AI search."],
  ["Missed opportunities", "Calls and enquiries disappear during busy hours or after hours with no system catching them.", "Capture and respond to every enquiry, regardless of channel or time."],
  ["Patient experience", "Communication gaps create a disjointed experience between enquiry, appointment, and follow-up.", "Keep communication consistent across the entire relationship."],
  ["Operational complexity", "Disconnected tools perform separate jobs without sharing useful information.", "Add the connective layer that makes existing tools function as one system."],
];

const businesses = ["Dental clinics", "Physiotherapy & chiropractic practices", "Pain management practices", "Med spas", "Wellness clinics", "Specialty practices"];

const systems = [
  ["Patient Revenue System", "The full definition of the connected system behind healthcare patient growth.", "/patient-revenue-system"],
  ["Patient Revenue System for Clinics", "How the system applies to independent clinic operations, with a direct path to assessment.", "/clinics"],
  ["Revenue Intelligence", "Understand where patient opportunities are won or lost across your systems.", "/revenue-intelligence"],
  ["Customer Progression", "See how patients move from enquiry to appointment to long-term relationship.", "/customer-progression"],
  ["AI Discovery", "Become visible across Google, AI Overviews, ChatGPT, and Gemini.", "/ai-discovery"],
];

const faqs = [
  ["What is healthcare operating intelligence?", "Healthcare Operating Intelligence connects digital discovery, patient communication, revenue systems, automation, and AI capabilities into one system that helps healthcare organizations operate more intelligently and consistently convert patient interest into booked care."],
  ["How can healthcare businesses get more patients?", "Often the fastest gains come from fixing response and follow-up gaps in the current patient journey rather than generating more traffic. Many practices already receive enquiries but lose a meaningful share to slow or inconsistent follow-up."],
  ["How does AI help healthcare practices?", "AI can respond instantly to a missed call, draft consistent follow-up messages, and summarize where a patient enquiry stands, freeing staff to focus on conversations and decisions that need human judgment."],
  ["What is a patient revenue system?", "A patient revenue system carries a patient from first search through to becoming a returning patient, connecting discovery, enquiry capture, communication, booking, and follow-up."],
  ["Why do healthcare businesses need automation?", "Manual follow-up depends on staff availability and memory. Automation applied to the right tasks, such as missed-call response and appointment reminders, keeps communication consistent when a practice is busy."],
  ["How is Flux different from healthcare marketing agencies?", "Most healthcare marketing agencies focus on generating traffic and leads. Flux focuses on the full system a patient moves through, including what happens after a lead arrives, where much of preventable patient loss occurs."],
  ["How can clinics improve patient experience?", "By making communication consistent from first enquiry through appointment and follow-up, so patients experience one coherent relationship instead of disconnected interactions."],
];

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <m.div initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .72, delay, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</m.div>;
}

function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) {
  return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className="flux-kicker text-flux">{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.5rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>;
}

function FluidShapes() {
  return <div className="pointer-events-none absolute inset-0 overflow-hidden" aria-hidden="true"><m.div animate={{ x: [0, -60, 20, 0], y: [0, 40, -20, 0], rotate: [0, 14, -8, 0], borderRadius: ["44% 56% 62% 38%", "61% 39% 45% 55%", "37% 63% 54% 46%", "44% 56% 62% 38%"] }} transition={{ duration: 20, repeat: Infinity, ease: "easeInOut" }} className="absolute -right-32 top-10 h-[30rem] w-[30rem] bg-pulse opacity-45 blur-3xl" /><m.div animate={{ x: [0, 45, -15, 0], y: [0, -30, 30, 0], scale: [1, 1.1, .95, 1] }} transition={{ duration: 24, repeat: Infinity, ease: "easeInOut" }} className="absolute -bottom-32 -left-24 h-80 w-80 rounded-full bg-flux/20 blur-3xl" /></div>;
}

export default function HealthcareIndustryPage() {
  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><FluidShapes /><div className="flux-shell relative z-10"><nav aria-label="Breadcrumb" className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/industries">Industries</Link><span className="mx-2">/</span><span>Healthcare</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.18fr_.82fr] lg:items-end lg:py-16"><m.div initial={{ opacity: 0, y: 38 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8 }}><p className="flux-kicker mb-7 text-flux">Healthcare operating intelligence</p><h1 className="max-w-6xl font-display text-[clamp(3.2rem,5.9vw,6.2rem)] font-medium leading-[.92] tracking-[-.07em]">Healthcare businesses need more than marketing. <span className="text-flux">They need intelligent growth systems.</span></h1></m.div><m.div initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .14, duration: .7 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Attracting attention has never been the hardest part of healthcare growth. Converting it into booked patients and keeping those patients engaged is where most healthcare businesses struggle.</p><p className="mt-5 text-lg leading-8 text-ink/65">Flux connects patient discovery, communication, revenue systems, automation, and AI capabilities into one system built for how patients find and choose care today.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/patient-revenue-system" className="flux-button flux-button-red">Explore Patient Revenue Systems <ArrowUpRight size={16} /></Link><Link href="/business-intelligence-audit" className="flux-button flux-button-line">Measure your intelligence score</Link></div></m.div></div><a href="#new-era" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">Explore healthcare growth <span className="flex h-10 w-10 items-center justify-center rounded-full border border-ink/15 transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-500 group-hover:translate-y-1 group-hover:bg-ink group-hover:text-white"><ArrowDownRight size={16} /></span></a></div></section>

    <PlatformEcosystem variant="industry" />

    <section id="new-era" className="bg-white py-16 md:py-20"><div className="flux-shell"><Heading eyebrow="A new growth era">Patients choose care differently now.</Heading><div className="mt-10 grid gap-8 lg:grid-cols-[.6fr_.4fr]"><Reveal className="space-y-6 text-xl leading-9 text-ink/65"><p>For years, healthcare growth followed referrals, advertising, a brochure-style website, and a front desk fielding calls.</p><p>That pattern has not disappeared, but it no longer describes how most patients find care. Patients search Google, check maps and reviews, and increasingly ask AI assistants directly for recommendations.</p><p>A patient may ask ChatGPT which pain management clinic nearby has the best reviews and never see a traditional list of search results.</p></Reveal><Reveal delay={.08} className="flex min-h-[320px] flex-col justify-between rounded-[2rem] bg-pulse p-8 text-white md:p-10"><p className="flux-kicker text-white/60">The visibility shift</p><p className="font-display text-4xl font-medium leading-tight text-white">Great care cannot win attention where the practice is invisible.</p><p className="text-sm leading-7 text-white/65">Referrals and a basic website are no longer enough on their own.</p></Reveal></div></div></section>

    <section className="bg-pulse-light py-16 md:py-20"><div className="flux-shell"><Heading eyebrow="The hidden problem">The individual pieces exist. The connection does not.</Heading><div className="mt-12 grid gap-6 lg:grid-cols-2"><Reveal className="rounded-[2rem] bg-white p-8 md:p-11"><p className="text-xl leading-9 text-ink/65">Most healthcare businesses have invested in a website, CRM or patient management system, advertising, and perhaps appointment reminders. Yet growth remains inconsistent because these pieces were not built to work together.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-ink p-8 text-white md:p-11"><p className="text-xl leading-9 text-white/65">A missed call receives no text-back. A website form enters no follow-up sequence. The gaps between systems are where patient opportunities quietly disappear—until the schedule looks thinner than it should.</p></Reveal></div></div></section>

    <section className="bg-white py-16 md:py-20"><div className="flux-shell"><Heading eyebrow="What it means">One connective layer for the whole patient growth system.</Heading><div className="mt-12 grid gap-10 lg:grid-cols-[.62fr_.38fr]"><Reveal className="space-y-6 text-xl leading-9 text-ink/65"><p>Healthcare Operating Intelligence connects digital discovery, patient communication, revenue systems, automation, and AI capabilities to help healthcare organizations operate more intelligently.</p><p>It is needed by any healthcare business that depends on new patient enquiries to fill its schedule. Most already have the individual components. What they lack is the connective layer that makes those components function as one system.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] border border-flux/25 bg-blush p-8 md:p-10"><p className="flux-kicker text-flux">Why it matters</p><p className="mt-10 font-display text-3xl font-medium leading-tight">A missed enquiry costs the lifetime value, referrals, and reviews that patient relationship could have created.</p></Reveal></div></div></section>

    <section className="relative overflow-hidden bg-ink py-16 text-white md:py-20"><FluidShapes /><div className="flux-shell relative z-10"><Heading eyebrow="The Flux framework" light>Five connected systems for modern healthcare growth.</Heading><div className="mt-14 grid border-t border-white/20">{framework.map(([number, title, body, href], index) => <Reveal key={title} delay={index * .04}><Link href={href} className="group grid gap-5 border-b border-white/20 py-8 transition-colors hover:bg-white hover:px-6 hover:text-ink md:grid-cols-[.12fr_.34fr_.46fr_.08fr] md:items-center"><span className="text-xs font-bold text-flux">{number}</span><h3 className="font-display text-2xl font-medium md:text-3xl">{title}</h3><p className="text-base leading-8 opacity-60">{body}</p><ArrowUpRight className="ml-auto transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /></Link></Reveal>)}</div></div></section>

    <section className="bg-cream py-16 md:py-20"><div className="flux-shell"><Heading eyebrow="Challenges we solve">Fix the system around patient demand.</Heading><div className="mt-12 grid gap-4 md:grid-cols-2">{challenges.map(([title, problem, solution], index) => <Reveal key={title} delay={index * .05} className="group rounded-[2rem] border border-ink/10 bg-white p-8 transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-500 hover:-translate-y-1 hover:border-flux/35 md:p-10"><span className="text-xs font-bold text-flux">0{index + 1}</span><h3 className="mt-8 font-display text-3xl font-medium">{title}</h3><p className="mt-5 leading-8 text-ink/55">{problem}</p><p className="mt-6 border-t border-ink/10 pt-5 font-semibold leading-7">{solution}</p></Reveal>)}</div></div></section>

    <section className="bg-pulse-light py-16 md:py-20"><div className="flux-shell"><Heading eyebrow="Healthcare businesses we support">Built around enquiry-led and appointment-based care.</Heading><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{businesses.map((item, index) => <Reveal key={item} delay={index * .04} className="flex min-h-[190px] flex-col justify-between rounded-[1.75rem] bg-white p-7 transition-transform duration-500 hover:-translate-y-2"><span className="text-xs font-bold text-flux">0{index + 1}</span><h3 className="font-display text-2xl font-medium">{item}</h3></Reveal>)}</div></div></section>

    <section className="bg-white py-16 md:py-20"><div className="flux-shell"><Heading eyebrow="Healthcare systems built by Flux">Move from industry context into the connected system.</Heading><div className="mt-12 grid border-t border-ink/15 md:grid-cols-2 lg:grid-cols-5">{systems.map(([title, body, href]) => <Link key={href} href={href} className="group flex min-h-[280px] flex-col justify-between border-b border-ink/15 p-7 transition-colors duration-500 hover:bg-ink hover:text-white md:border-r"><ArrowUpRight className="ml-auto text-flux transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /><div><h3 className="font-display text-2xl font-medium">{title}</h3><p className="mt-4 text-sm leading-7 opacity-55">{body}</p></div></Link>)}</div></div></section>

    <section className="relative overflow-hidden bg-pulse py-16 text-white md:py-20"><FluidShapes /><div className="flux-shell relative z-10"><Heading eyebrow="AI visibility" light>Healthcare practices must be understandable, not only rankable.</Heading><div className="mt-10 grid gap-10 lg:grid-cols-[.6fr_.4fr]"><Reveal className="space-y-6 text-xl leading-9 text-white/70"><p>Health decisions are exactly the kind of questions people now bring directly to AI assistants. Patients ask which practice is best for anxious patients or which clinic specializes in a condition, then act on the answer without seeing a traditional search page.</p><p>Healthcare businesses need clear, consistent, structured information about what they do, whom they serve, and what patients say—published where AI systems draw their understanding.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-ink p-8 text-white md:p-10"><p className="flux-kicker text-flux">The new requirement</p><p className="mt-10 font-display text-4xl font-medium leading-tight text-white">Invisible to the AI layer means invisible to a growing share of patients.</p><Link href="/ai-discovery" className="flux-button mt-10 bg-white text-ink">Explore AI Discovery <ArrowUpRight size={16} /></Link></Reveal></div></div></section>

    <section className="bg-cream py-16 md:py-20"><div className="flux-shell"><Heading eyebrow="FAQ">Healthcare operating intelligence, explained.</Heading><div className="mt-12 divide-y divide-ink/15 border-y border-ink/15">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-ink/15 transition-transform duration-500 group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>

    <section className="relative overflow-hidden bg-flux py-16 text-white md:py-20"><m.div animate={{ rotate: 360 }} transition={{ duration: 38, repeat: Infinity, ease: "linear" }} className="absolute -right-40 -top-40 h-[34rem] w-[34rem] rounded-[42%_58%_66%_34%] border border-white/25" /><div className="flux-shell relative z-10"><p className="flux-kicker text-white/65">Explore Patient Revenue Systems</p><Reveal><h2 className="mt-7 max-w-6xl font-display text-[clamp(3rem,5.5vw,5.7rem)] font-medium leading-[.95] tracking-[-.06em]">Connect discovery, communication, booking, and follow-up.</h2></Reveal><p className="mt-8 max-w-3xl text-xl leading-9 text-white/70">See the full framework behind how Flux connects the patient growth system—or measure where your practice stands today.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/patient-revenue-system" className="flux-button bg-white text-ink">Explore Patient Revenue Systems <ArrowUpRight size={16} /></Link><Link href="/business-intelligence-audit" className="flux-button border border-white/35 text-white">Measure your intelligence score</Link></div></div></section>
  </>;
}
