"use client";

import Link from "next/link";
import { m } from "framer-motion";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";

const lossPoints = [
  ["01", "Discovery", "Customers cannot find you, or your online presence does not clearly explain what you do, where you serve, and why they should trust you."],
  ["02", "Response", "A missed call on a job site, unanswered form, or slow quote reply sends the work to whichever company answers first."],
  ["03", "Booking", "An estimate that requires too much back-and-forth loses customers who were ready to proceed but did not want to wait."],
  ["04", "Follow-up", "A quote with no follow-up plan disappears even when the customer is genuinely still deciding."],
];

const connectedSystems = [
  ["Revenue Intelligence", "See where jobs come from and where they are lost by connecting website, call, and CRM data into one view.", "/revenue-intelligence"],
  ["Customer Progression", "Give every quote request and estimate a fast response and consistent follow-up until the customer decides.", "/customer-progression"],
  ["AI Discovery", "Show up where homeowners look across Google, local maps, and AI tools used for contractor recommendations.", "/ai-discovery"],
];

const businesses = [
  ["HVAC companies", "Emergency repairs and scheduled installation quotes"],
  ["Plumbers", "Urgent service calls and larger project estimates"],
  ["Roofers", "High-value quote requests where one missed response matters"],
  ["General contractors", "Longer sales cycles across multiple active estimates"],
  ["Other home services", "Any service where response speed and follow-up determine booked work"],
];

const related = [
  ["Revenue Intelligence", "Understand which jobs come from where and where quotes stall.", "/revenue-intelligence"],
  ["Customer Progression", "Give every quote request a fast response and reliable follow-up.", "/customer-progression"],
  ["AI Discovery", "Become visible across Google, maps, and AI assistants.", "/ai-discovery"],
  ["Operating Intelligence", "See the connected operating system these layers belong to.", "/operating-intelligence"],
  ["Business Intelligence Audit", "Find where your current system is losing jobs.", "/business-intelligence-audit"],
];

const faqs = [
  ["Why am I getting calls and quote requests but not enough booked jobs?", "Usually because of a gap between the enquiry and booking, not a lack of interest: slow response times, no follow-up on estimates that do not convert immediately, or a booking process requiring too much back-and-forth."],
  ["How can automation help a home service business specifically?", "Automated missed-call text-back and quote follow-up recover jobs currently lost to slow response without requiring extra staff or hours. The system handles the immediate response while your team is on the job."],
  ["Do I need a new website, or can this connect to what I already have?", "It depends on whether your current site clearly explains what you do and makes requesting a quote easy. If it does, response and follow-up systems can usually connect directly. If it does not convert well, a rebuild may be recommended."],
  ["How is this different from a typical home services marketing agency?", "Most agencies focus on generating more calls and quote requests. This approach focuses on what happens after the request arrives, where a larger share of preventable lost jobs usually occurs."],
  ["How quickly can this be set up?", "Most home service businesses are live within one to two weeks, depending on how much of the system must be built new versus connected to tools already in use."],
];

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <m.div initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .72, delay, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</m.div>;
}

function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) {
  return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className="flux-kicker text-flux">{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.5rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>;
}

function FluidShapes() {
  return <div className="pointer-events-none absolute inset-0 overflow-hidden" aria-hidden="true"><m.div animate={{ x: [0, -55, 25, 0], y: [0, 45, -15, 0], rotate: [0, 15, -7, 0], borderRadius: ["40% 60% 67% 33%", "63% 37% 42% 58%", "35% 65% 57% 43%", "40% 60% 67% 33%"] }} transition={{ duration: 19, repeat: Infinity, ease: "easeInOut" }} className="absolute -right-28 top-12 h-[30rem] w-[30rem] bg-pulse opacity-50 blur-3xl" /><m.div animate={{ x: [0, 50, -10, 0], y: [0, -25, 35, 0], scale: [1, 1.12, .95, 1] }} transition={{ duration: 23, repeat: Infinity, ease: "easeInOut" }} className="absolute -bottom-36 -left-24 h-80 w-80 rounded-full bg-flux/20 blur-3xl" /></div>;
}

export default function HomeServicesIndustryPage() {
  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><FluidShapes /><div className="flux-shell relative z-10"><nav aria-label="Breadcrumb" className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/industries">Industries</Link><span className="mx-2">/</span><span>Home Services</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.18fr_.82fr] lg:items-end lg:py-16"><m.div initial={{ opacity: 0, y: 38 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8 }}><p className="flux-kicker mb-7 text-flux">Home service growth systems</p><h1 className="max-w-6xl font-display text-[clamp(3.3rem,6.1vw,6.4rem)] font-medium leading-[.92] tracking-[-.07em]">More estimates don&apos;t fill your schedule. <span className="text-flux">A connected system does.</span></h1></m.div><m.div initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .14, duration: .7 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Home service businesses do not usually struggle to generate interest. What determines whether enquiries become booked jobs is response speed, easy booking, and reliable follow-up.</p><p className="mt-5 text-lg leading-8 text-ink/65">Flux connects discovery, communication, and follow-up into one system that turns more existing enquiries into booked work.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/revenue-intelligence" className="flux-button flux-button-red">Explore Revenue Intelligence <ArrowUpRight size={16} /></Link><Link href="/business-intelligence-audit" className="flux-button flux-button-line">Measure your intelligence score</Link></div></m.div></div><a href="#lost-job" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">Follow the lost job <span className="flex h-10 w-10 items-center justify-center rounded-full border border-ink/15 transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-500 group-hover:translate-y-1 group-hover:bg-ink group-hover:text-white"><ArrowDownRight size={16} /></span></a></div></section>

    <section id="lost-job" className="bg-white py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="The job you are losing">The call came in. The booking did not.</Heading><div className="mt-12 grid gap-8 lg:grid-cols-[.62fr_.38fr]"><Reveal className="space-y-6 text-xl leading-9 text-ink/65"><p>Most home service businesses assume a slow month means not enough calls came in. Often, the calls came in fine. The job was lost somewhere between the call and the booking.</p><p>A homeowner calls during a busy afternoon on a job site. Nobody picks up, so they call the next company. A quote request arrives at 8pm and receives a reply two days later. An estimate goes out without follow-up and the customer simply never moves forward.</p><p>None of this appears as a marketing problem. It appears as a quieter week and gets blamed on demand, when demand was there the whole time.</p></Reveal><Reveal delay={.08} className="flex min-h-[360px] flex-col justify-between rounded-[2rem] bg-flux p-8 text-white md:p-10"><p className="flux-kicker text-white/60">The hidden loss</p><p className="font-display text-4xl font-medium leading-tight">The job was not lost before the call. It was lost after interest appeared.</p><p className="text-sm leading-7 text-white/70">Response and follow-up determine who gets on the schedule.</p></Reveal></div></div></section>

    <section className="bg-pulse-light py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="Where jobs disappear">Four small gaps compound into significant lost revenue.</Heading><div className="mt-12 grid gap-4 md:grid-cols-2">{lossPoints.map(([number, title, body], index) => <Reveal key={title} delay={index * .05} className="group rounded-[2rem] bg-white p-8 transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-500 hover:-translate-y-1 hover:shadow-[0_22px_70px_rgba(6,7,10,.08)] md:p-10"><span className="text-xs font-bold text-flux">{number}</span><h3 className="mt-9 font-display text-3xl font-medium">{title}</h3><p className="mt-5 text-base leading-8 text-ink/60">{body}</p></Reveal>)}</div><p className="mt-10 max-w-4xl text-xl leading-9 text-ink/65">Across a full year of calls and quotes, these gaps usually represent more lost revenue than additional ad spend could recover.</p></div></section>

    <section className="relative overflow-hidden bg-ink py-20 text-white md:py-28"><FluidShapes /><div className="flux-shell relative z-10"><Heading eyebrow="How Flux connects it" light>One path from homeowner search to booked job.</Heading><div className="mt-14 grid gap-4 lg:grid-cols-3">{connectedSystems.map(([title, body, href], index) => <Reveal key={title} delay={index * .06}><Link href={href} className="group flex min-h-[360px] flex-col justify-between rounded-[2rem] border border-white/20 p-8 transition-colors duration-500 hover:bg-white hover:text-ink"><div className="flex items-center justify-between"><span className="text-xs font-bold text-flux">0{index + 1}</span><ArrowUpRight className="transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /></div><div><h3 className="font-display text-3xl font-medium">{title}</h3><p className="mt-5 text-base leading-8 opacity-60">{body}</p></div></Link></Reveal>)}</div><p className="mt-10 max-w-4xl text-xl leading-9 text-white/60">Connected together, these layers cover the full path from a homeowner searching for help to a job on your schedule.</p></div></section>

    <section className="bg-white py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="What it looks like in practice">Fast response without adding staff or hours.</Heading><div className="mt-12 grid gap-4 lg:grid-cols-3">{[["Missed call", "An automatic text responds within a minute, so the homeowner knows you received it instead of assuming nobody is answering."], ["After-hours quote", "A request submitted at night enters the system and receives the right response instead of waiting unnoticed for two days."], ["Open estimate", "A quote that does not convert immediately gets a planned follow-up instead of disappearing when the conversation goes quiet."]].map(([title, body], index) => <Reveal key={title} delay={index * .06} className="rounded-[2rem] border border-ink/10 p-8 md:p-10"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-flux text-xs font-bold text-white">0{index + 1}</span><h3 className="mt-9 font-display text-3xl font-medium">{title}</h3><p className="mt-5 text-base leading-8 text-ink/60">{body}</p></Reveal>)}</div><p className="mt-10 max-w-4xl text-xl leading-9 text-ink/65">The website, phone, and CRM work together so customer interest no longer depends on which employee happens to be available.</p></div></section>

    <section className="bg-cream py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="Businesses we support">For trades where slow response directly costs booked work.</Heading><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{businesses.map(([title, body], index) => <Reveal key={title} delay={index * .04} className="flex min-h-[250px] flex-col justify-between rounded-[1.75rem] bg-white p-7 transition-transform duration-500 hover:-translate-y-2"><span className="text-xs font-bold text-flux">0{index + 1}</span><div><h3 className="font-display text-2xl font-medium">{title}</h3><p className="mt-4 text-sm leading-7 text-ink/50">{body}</p></div></Reveal>)}</div></div></section>

    <section className="bg-pulse-light py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="Related systems">Continue through the connected home service system.</Heading><div className="mt-12 grid border-t border-ink/15 md:grid-cols-2 lg:grid-cols-5">{related.map(([title, body, href]) => <Link key={href} href={href} className="group flex min-h-[280px] flex-col justify-between border-b border-ink/15 p-7 transition-colors duration-500 hover:bg-ink hover:text-white md:border-r"><ArrowUpRight className="ml-auto text-flux transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /><div><h3 className="font-display text-2xl font-medium">{title}</h3><p className="mt-4 text-sm leading-7 opacity-55">{body}</p></div></Link>)}</div></div></section>

    <section className="bg-white py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="FAQ">Questions about home service growth systems.</Heading><div className="mt-12 divide-y divide-ink/15 border-y border-ink/15">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-ink/15 transition-transform duration-500 group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>

    <section className="relative overflow-hidden bg-flux py-20 text-white md:py-28"><m.div animate={{ rotate: 360 }} transition={{ duration: 38, repeat: Infinity, ease: "linear" }} className="absolute -right-40 -top-40 h-[34rem] w-[34rem] rounded-[42%_58%_66%_34%] border border-white/25" /><div className="flux-shell relative z-10"><p className="flux-kicker text-white/65">Business Intelligence Audit</p><Reveal><h2 className="mt-7 max-w-6xl font-display text-[clamp(3rem,5.5vw,5.7rem)] font-medium leading-[.95] tracking-[-.06em]">See where calls and quotes become booked jobs—and where they don&apos;t.</h2></Reveal><p className="mt-8 max-w-3xl text-xl leading-9 text-white/70">Measure your Business Intelligence Score. No obligation, and we respond within 24 hours.</p><Link href="/business-intelligence-audit" className="flux-button mt-10 bg-white text-ink">Measure your intelligence score <ArrowUpRight size={16} /></Link></div></section>
  </>;
}
