"use client";

import Link from "next/link";
import { m } from "framer-motion";
import { ArrowDownRight, ArrowUpRight } from "@/components/ui/animated-icons";
import PlatformEcosystem from "@/components/brand/PlatformEcosystem";

const journey = [
  ["01", "Discovery", "A prospective client searches through Google, referrals, review sites, or an AI assistant. Most legal marketing investment is concentrated here."],
  ["02", "Research", "They compare firms, read reviews and case results, and decide who appears to understand their specific situation."],
  ["03", "Consultation request", "They reach out by phone, form, chat, or referral. This is where firms have the least room for error and often lose the most opportunity."],
  ["04", "Communication", "Between inquiry and consultation, silence, delay, or inconsistent information can push a potential client toward another firm."],
  ["05", "Decision", "The client chooses based on responsiveness, clarity, and confidence that the firm will handle their matter well."],
  ["06", "Client relationship", "Communication through the case shapes reviews, referrals, and repeat business for recurring legal needs."],
];

const framework = [
  ["01", "Legal Discovery Intelligence", "Search visibility for priority practice areas, structured content AI systems can understand, reputation signals, and a consistent representation of the firm's authority.", "/ai-discovery"],
  ["02", "Client Intake Intelligence", "Call routing, form capture, qualification, and response systems designed around how quickly prospective legal clients actually make decisions.", "/customer-progression"],
  ["03", "Revenue Intelligence", "Connect marketing spend, inquiry data, consultations, and case outcomes to understand what is driving retained business rather than traffic alone.", "/revenue-intelligence"],
  ["04", "Client Progression", "Structured follow-up and status communication that keeps prospective and current clients informed throughout the relationship.", "/customer-progression"],
  ["05", "Operational Intelligence", "Workflows and automation that connect intake, case management, and communications while giving partners visibility into response time, open inquiries, and workload.", "/operating-intelligence"],
];

const practices = [
  ["Personal injury law", "Response time to a new inquiry can determine whether a case gets signed."],
  ["Family law", "Sensitive, high-emotion inquiries need consistent and clear communication from first contact."],
  ["Immigration law", "Long timelines require structured follow-up to keep clients informed and engaged."],
  ["Estate planning", "Trust and clarity during intake directly affect conversion."],
  ["Criminal defense", "Time-sensitive inquiries require rapid, prioritized response."],
  ["Business law", "Client relationships often span recurring matters rather than one case."],
  ["Employment law", "High inquiry volume requires consistent qualification to focus attorney time."],
];

const faqs = [
  ["What is Operating Intelligence for law firms?", "Operating Intelligence for law firms connects how a firm is discovered, how it handles intake and communication, and how it manages workflows and data internally. It gives the firm visibility into where clients are gained or lost."],
  ["How can law firms improve client intake?", "Firms improve intake through consistent response times, structured qualification, follow-up sequences that prevent inquiries going cold, and visibility into open inquiries and wait times."],
  ["Why do law firms lose potential clients?", "Most are lost to slow response, inconsistent communication, fragmented processes between intake and case management, and a lack of visibility into where inquiries stall."],
  ["How can AI help attorneys?", "AI can structure intake conversations, answer routine client questions, support preliminary research, and improve AI-search visibility, while attorneys retain final legal judgment."],
  ["What technology should modern law firms use?", "The most useful technology connects the firm's existing website, intake forms, phone systems, and case-management software rather than adding another isolated tool."],
  ["How can law firms prepare for the future?", "Connect discovery, intake, and communication now; structure online information for search and AI systems; and measure operational visibility alongside traffic and ad spend."],
];

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <m.div initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .1 }} transition={{ duration: .72, delay, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</m.div>;
}
function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) {
  return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className="flux-kicker text-flux">{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.5rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>;
}
function FluidShapes() {
  return <div className="pointer-events-none absolute inset-0 overflow-hidden" aria-hidden="true"><m.div animate={{ x: [0, -55, 20, 0], y: [0, 40, -18, 0], rotate: [0, 15, -9, 0], borderRadius: ["43% 57% 66% 34%", "61% 39% 43% 57%", "36% 64% 55% 45%", "43% 57% 66% 34%"] }} transition={{ duration: 20, repeat: Infinity, ease: "easeInOut" }} className="absolute -right-28 top-10 h-[30rem] w-[30rem] bg-pulse opacity-45 blur-3xl" /><m.div animate={{ x: [0, 45, -12, 0], y: [0, -28, 32, 0], scale: [1, 1.1, .95, 1] }} transition={{ duration: 24, repeat: Infinity, ease: "easeInOut" }} className="absolute -bottom-32 -left-24 h-80 w-80 rounded-full bg-flux/20 blur-3xl" /></div>;
}

export default function LegalIndustryPage() {
  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><FluidShapes /><div className="flux-shell relative z-10"><nav aria-label="Breadcrumb" className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/industries">Industries</Link><span className="mx-2">/</span><span>Legal</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.18fr_.82fr] lg:items-end lg:py-16"><m.div initial={{ opacity: 0, y: 38 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8 }}><p className="flux-kicker mb-7 text-flux">Legal operating intelligence</p><h1 className="max-w-6xl font-display text-[clamp(3.2rem,5.9vw,6.2rem)] font-medium leading-[.92] tracking-[-.07em]">Law firms don&apos;t have a marketing problem. <span className="text-flux">They have a connected systems problem.</span></h1></m.div><m.div initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .14, duration: .7 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Most firms are not short on visibility. What separates growing firms is what happens after someone finds them: response speed, consistent intake, clear client progression, and visibility into where opportunities are lost.</p><p className="mt-5 text-lg leading-8 text-ink/65">Flux connects legal discovery, client intake, communication, and business operations into one operating intelligence system.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/business-intelligence-audit" className="flux-button flux-button-red">Measure your intelligence score <ArrowUpRight size={16} /></Link><Link href="/contact" className="flux-button flux-button-line">Talk to Flux about your firm</Link></div></m.div></div><a href="#hidden-problem" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">Follow the client journey <span className="flex h-10 w-10 items-center justify-center rounded-full border border-ink/15 transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-500 group-hover:translate-y-1 group-hover:bg-ink group-hover:text-white"><ArrowDownRight size={16} /></span></a></div></section>

    <PlatformEcosystem variant="industry" />

    <section id="hidden-problem" className="bg-white py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="The hidden growth problem">The firm gets found. The work is lost afterward.</Heading><div className="mt-12 grid gap-8 lg:grid-cols-[.62fr_.38fr]"><Reveal className="space-y-6 text-xl leading-9 text-ink/65"><p>Managing partners usually ask for more cases, so firms invest in paid search, SEO, content, and regular website redesigns. That spending is not wasted, but for many firms it is not where the central leak exists.</p><p>A paid call reaches voicemail. A family-law form submitted at 9 p.m. waits two days. An incomplete immigration intake is deprioritized. An urgent criminal-defense inquiry enters the same queue as a billing question.</p><p>These are downstream operational and communication failures. Firms may track ad spend and cost per lead while lacking visibility into timely response, proper qualification, and inquiries that went cold after one attempt.</p></Reveal><Reveal delay={.08} className="flex min-h-[390px] flex-col justify-between rounded-[2rem] bg-flux p-8 text-white md:p-10"><p className="flux-kicker text-white/60">Not a visibility problem</p><p className="font-display text-4xl font-medium leading-tight">The firm did the work to get found. It lost the work after it was found.</p><p className="text-sm leading-7 text-white/70">Marketing cannot repair an intake system it cannot see.</p></Reveal></div></div></section>

    <section className="bg-pulse-light py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="The client journey">Growth is determined by value retained at every step.</Heading><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{journey.map(([number, title, body], index) => <Reveal key={title} delay={index * .04} className="flex min-h-[280px] flex-col justify-between rounded-[2rem] bg-white p-8 transition-transform duration-500 hover:-translate-y-1"><span className="text-xs font-bold text-flux">{number}</span><div><h3 className="font-display text-3xl font-medium">{title}</h3><p className="mt-5 leading-8 text-ink/58">{body}</p></div></Reveal>)}</div><p className="mt-10 max-w-5xl text-xl leading-9 text-ink/65">A strategy that optimizes discovery while leaving intake and communication disconnected will underperform, regardless of how much traffic supports it.</p></div></section>

    <section className="bg-white py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="What it is">The connective layer beneath discovery, intake, communication, and case workflows.</Heading><div className="mt-12 grid gap-10 lg:grid-cols-[.58fr_.42fr]"><Reveal className="space-y-6 text-xl leading-9 text-ink/65"><p>Legal Operating Intelligence connects how a firm is discovered, how it communicates with prospective and current clients, how it manages intake and workflows, and how it uses data and AI to improve the whole system.</p><p>It is not one tool. It allows information to move automatically rather than relying on staff to manually transfer it between website forms, phone notes, and case-management systems.</p><p>The firm gains visibility into inquiry sources, response time, qualification, open opportunities, stalled follow-up, and which channels produce consultations and signed clients.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-ink p-8 text-white md:p-10"><p className="flux-kicker text-flux">Connected intelligence</p><ul className="mt-10 space-y-5 text-base leading-8 text-white/65"><li>Consistent capture and routing</li><li>Scheduled follow-up</li><li>Less duplicate data entry</li><li>Visible inquiry stages and wait times</li><li>Decisions based on retained business</li></ul><Link href="/operating-intelligence" className="flux-button mt-10 bg-white text-ink">Explore Operating Intelligence <ArrowUpRight size={16} /></Link></Reveal></div></div></section>

    <section className="relative overflow-hidden bg-ink py-20 text-white md:py-28"><FluidShapes /><div className="flux-shell relative z-10"><Heading eyebrow="The Flux legal framework" light>Five layers that make legal growth compound.</Heading><div className="mt-14 grid border-t border-white/20">{framework.map(([number, title, body, href], index) => <Reveal key={title} delay={index * .04}><Link href={href} className="group grid gap-5 border-b border-white/20 py-8 transition-colors hover:bg-white hover:px-6 hover:text-ink md:grid-cols-[.1fr_.32fr_.5fr_.08fr] md:items-center"><span className="text-xs font-bold text-flux">{number}</span><h3 className="font-display text-2xl font-medium md:text-3xl">{title}</h3><p className="leading-8 opacity-60">{body}</p><ArrowUpRight className="ml-auto transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /></Link></Reveal>)}</div></div></section>

    <section className="bg-cream py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="Why marketing is not enough">More inquiries are an input, not the complete strategy.</Heading><div className="mt-12 grid gap-5 lg:grid-cols-2"><Reveal className="rounded-[2rem] bg-white p-8 md:p-11"><p className="flux-kicker text-ink/40">Traditional legal growth</p><p className="mt-10 font-display text-4xl font-medium">Spend. Generate inquiries. Assume intake handles the rest.</p><p className="mt-8 text-lg leading-9 text-ink/60">This model is not designed for clients comparing several firms simultaneously and expecting responses within minutes.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-flux p-8 text-white md:p-11"><p className="flux-kicker text-white/60">Connected legal growth</p><p className="mt-10 font-display text-4xl font-medium">Measure response. Qualify consistently. Follow up. Connect outcomes.</p><p className="mt-8 text-lg leading-9 text-white/70">A firm with fewer inquiries and a strong intake system can outperform one generating twice the volume without structured follow-up.</p></Reveal></div><p className="mt-10 max-w-5xl text-xl leading-9 text-ink/65">Measure response time, second follow-up rates, qualified-inquiry consultation rates, retained cases, and referrals alongside clicks and cost per lead.</p></div></section>

    <section className="relative overflow-hidden bg-pulse py-20 md:py-28"><FluidShapes /><div className="flux-shell relative z-10"><Heading eyebrow="AI and legal businesses">Use automation to improve response and clarity, not replace legal judgment.</Heading><div className="mt-12 grid gap-10 lg:grid-cols-[.6fr_.4fr]"><Reveal className="space-y-6 text-xl leading-9 text-ink/65"><p>Legal research increasingly begins with questions asked of AI assistants. Clear, factual, structured practice-area content makes a firm more likely to be understood and referenced accurately.</p><p>Inside the firm, AI can structure intake conversations, support preliminary research, answer routine scheduling or process questions, and summarize inquiry status. Attorneys still review and make decisions requiring legal expertise.</p><p>The firms adapting well are not necessarily using the most AI tools. They know where AI improves speed and accuracy and where human judgment and client relationships must lead.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-ink p-8 text-white md:p-10"><p className="flux-kicker text-flux">The operating principle</p><p className="mt-10 font-display text-4xl font-medium leading-tight">Strengthen legal work around the attorney. Do not automate around legal judgment.</p><Link href="/ai-discovery" className="flux-button mt-10 bg-white text-ink">Explore AI Discovery <ArrowUpRight size={16} /></Link></Reveal></div></div></section>

    <section className="bg-white py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="Legal businesses Flux supports">Different practice areas. The same underlying systems challenge.</Heading><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{practices.map(([title, body], index) => <Reveal key={title} delay={index * .035} className="flex min-h-[260px] flex-col justify-between rounded-[1.75rem] border border-ink/10 p-7 transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-500 hover:-translate-y-1 hover:border-flux/35"><span className="text-xs font-bold text-flux">0{index + 1}</span><div><h3 className="font-display text-2xl font-medium">{title}</h3><p className="mt-4 text-sm leading-7 text-ink/55">{body}</p></div></Reveal>)}</div></div></section>

    <section className="bg-ink py-20 text-white md:py-28"><div className="flux-shell"><Heading eyebrow="Built on Flux Operating Intelligence" light>The legal application of a broader connected system.</Heading><div className="mt-12 grid gap-8 lg:grid-cols-[.58fr_.42fr]"><Reveal className="space-y-6 text-xl leading-9 text-white/60"><p>Law firms are service businesses with complex client journeys, high-stakes communication requirements, and increasing competition across search and AI recommendations.</p><p>The principles are consistent: connect discovery to intake, intake to communication, and communication to operational visibility. Use automation and AI to strengthen the connection rather than replace the people running the practice.</p><p>The same system applies across a <Link className="text-white underline underline-offset-4" href="/industries/home-services">home services business</Link> or <Link className="text-white underline underline-offset-4" href="/industries/healthcare">healthcare practice</Link>, adapted to the way its customers search, decide, and progress.</p></Reveal><div className="grid gap-3">{[["Revenue Intelligence", "/revenue-intelligence"], ["Customer Progression", "/customer-progression"], ["AI Discovery", "/ai-discovery"], ["Operating Intelligence", "/operating-intelligence"], ["Business Intelligence Audit", "/business-intelligence-audit"]].map(([title, href], index) => <Reveal key={href} delay={index * .04}><Link href={href} className="group flex items-center justify-between rounded-2xl border border-white/20 p-5 transition-colors hover:bg-white hover:text-ink"><span className="font-display text-xl font-medium">{title}</span><ArrowUpRight className="text-flux transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /></Link></Reveal>)}</div></div></div></section>

    <section className="bg-cream py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="FAQ">Legal operating intelligence, explained.</Heading><div className="mt-12 divide-y divide-ink/15 border-y border-ink/15">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-ink/15 transition-transform duration-500 group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>

    <section className="relative overflow-hidden bg-flux py-20 text-white md:py-28"><m.div animate={{ rotate: 360 }} transition={{ duration: 38, repeat: Infinity, ease: "linear" }} className="absolute -right-40 -top-40 h-[34rem] w-[34rem] rounded-[42%_58%_66%_34%] border border-white/25" /><div className="flux-shell relative z-10"><p className="flux-kicker text-white/65">Business Intelligence Audit</p><Reveal><h2 className="mt-7 max-w-6xl font-display text-[clamp(3rem,5.5vw,5.7rem)] font-medium leading-[.95] tracking-[-.06em]">Find where inquiries, revenue, and client relationships are being lost.</h2></Reveal><p className="mt-8 max-w-3xl text-xl leading-9 text-white/70">Map your current client journey against the five layers of the Legal Intelligence Framework.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/business-intelligence-audit" className="flux-button bg-white text-ink">Measure your intelligence score <ArrowUpRight size={16} /></Link><Link href="/contact" className="flux-button border border-white/35 text-white">Talk to Flux about your firm</Link></div></div></section>
  </>;
}
