"use client";

import Link from "next/link";
import { m } from "framer-motion";
import { ArrowDownRight, ArrowUpRight } from "@/components/ui/animated-icons";
import PlatformEcosystem from "@/components/brand/PlatformEcosystem";

const journey = [
  ["01", "Discovery", "A potential client finds the business through search, social, referrals, reviews, or an AI assistant summarizing options."],
  ["02", "Trust", "They evaluate whether the business understands their goal, whether results feel credible, and whether the experience is worth the cost and time."],
  ["03", "First booking", "The client commits to an initial visit, class, or consultation. In a relationship business, this is the starting point rather than the finish line."],
  ["04", "Experience", "The quality of the visit shapes intent to return, but experience alone rarely produces a second booking without a clear next step."],
  ["05", "Follow-up", "A timely and relevant follow-up raises the chance of a second visit. A missed one is where many relationships quietly end."],
  ["06", "Repeat visit", "The client returns on a cadence matching the service: weekly, monthly, or seasonal."],
  ["07", "Long-term relationship", "The client becomes a member, regular, or referral source when the business keeps the relationship active."],
];

const framework = [
  ["01", "Wellness Discovery Intelligence", "Search visibility, AI discovery, specific service content, and a credible reputation across the channels clients use to research wellness options.", "/ai-discovery"],
  ["02", "Customer Experience Intelligence", "Simple booking, clear pre-visit communication, and personalized experiences informed by client history and preferences.", "/customer-progression"],
  ["03", "Revenue Intelligence", "Connect booking data, service history, channels, and client value to distinguish long-term relationships from one-time visits.", "/revenue-intelligence"],
  ["04", "Customer Progression", "Structured post-visit follow-up, service-cadence rebooking, renewals, and communication that turns first visits into lasting relationships.", "/customer-progression"],
  ["05", "Operational Intelligence", "Connect booking, communications, and customer records while reducing repetitive work and revealing retention, no-show, and utilization patterns.", "/operating-intelligence"],
];

const businesses = [
  ["Med spas", "Treatment cadence and follow-up timing directly affect repeat revenue."],
  ["Wellness clinics", "Trust and clear communication support treatment-plan continuity."],
  ["Fitness businesses", "Retention depends on engagement between visits, not only the workout."],
  ["Yoga studios", "Attendance patterns can reveal disengagement before cancellation."],
  ["Pilates studios", "Personalized progression supports long-term membership value."],
  ["Nutrition businesses", "Ongoing accountability matters beyond the initial consultation."],
  ["Recovery centers", "Timely follow-up affects experience and retention."],
  ["Beauty wellness brands", "Repeat purchase and rebooking depend on well-timed personalization."],
  ["Holistic health businesses", "Trust and consistent relationships are central to growth."],
];

const faqs = [
  ["What is Operating Intelligence for wellness businesses?", "It connects how a business is discovered, how it understands and communicates with customers, and how it manages experience and retention systems, revealing where relationships strengthen or disappear."],
  ["How can wellness businesses increase customer retention?", "Make follow-up consistent after every visit, time rebooking prompts to the service cadence, personalize communication from real client history, and identify early signs of disengagement."],
  ["Why do wellness businesses lose customers?", "Most are lost to disconnected experiences, inconsistent post-visit communication, generic follow-up, and systems that leave rebooking to chance."],
  ["How can AI help wellness companies?", "AI can personalize recommendations, automate reminders and rebooking prompts, assist with support, and improve AI-search understanding while staff and practitioners lead the relationship."],
  ["What systems do modern wellness businesses need?", "Systems that connect existing booking software, communication channels, and customer records are more valuable than another isolated platform."],
  ["How can wellness businesses improve customer experience?", "Give staff full client context, keep pre- and post-appointment communication timely, and personalize recommendations using customer history."],
];

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <m.div initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .1 }} transition={{ duration: .72, delay, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</m.div>;
}
function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) {
  return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className="flux-kicker text-flux">{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.5rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>;
}
function FluidShapes() {
  return <div className="pointer-events-none absolute inset-0 overflow-hidden" aria-hidden="true"><m.div animate={{ x: [0, -60, 22, 0], y: [0, 42, -16, 0], rotate: [0, 16, -8, 0], borderRadius: ["44% 56% 64% 36%", "62% 38% 43% 57%", "36% 64% 56% 44%", "44% 56% 64% 36%"] }} transition={{ duration: 21, repeat: Infinity, ease: "easeInOut" }} className="absolute -right-28 top-10 h-[30rem] w-[30rem] bg-pulse opacity-50 blur-3xl" /><m.div animate={{ x: [0, 48, -12, 0], y: [0, -30, 32, 0], scale: [1, 1.12, .95, 1] }} transition={{ duration: 25, repeat: Infinity, ease: "easeInOut" }} className="absolute -bottom-32 -left-24 h-80 w-80 rounded-full bg-flux/20 blur-3xl" /></div>;
}

export default function WellnessIndustryPage() {
  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><FluidShapes /><div className="flux-shell relative z-10"><nav aria-label="Breadcrumb" className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/industries">Industries</Link><span className="mx-2">/</span><span>Wellness</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.18fr_.82fr] lg:items-end lg:py-16"><m.div initial={{ opacity: 0, y: 38 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8 }}><p className="flux-kicker mb-7 text-flux">Wellness operating intelligence</p><h1 className="max-w-6xl font-display text-[clamp(3.2rem,5.9vw,6.2rem)] font-medium leading-[.92] tracking-[-.07em]">Wellness businesses don&apos;t have a bookings problem. <span className="text-flux">They have a relationship problem.</span></h1></m.div><m.div initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .14, duration: .7 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Most wellness businesses can generate a first visit. Growth is determined by what happens afterward: follow-up, rebooking, communication between visits, and seeing which clients may lapse before they disappear.</p><p className="mt-5 text-lg leading-8 text-ink/65">Flux connects discovery, customer experience, communication, and retention into one system.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/business-intelligence-audit" className="flux-button flux-button-red">Measure your intelligence score <ArrowUpRight size={16} /></Link><Link href="/contact" className="flux-button flux-button-line">Talk to Flux about your business</Link></div></m.div></div><a href="#hidden-challenge" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">Follow the relationship <span className="flex h-10 w-10 items-center justify-center rounded-full border border-ink/15 transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-500 group-hover:translate-y-1 group-hover:bg-ink group-hover:text-white"><ArrowDownRight size={16} /></span></a></div></section>

    <PlatformEcosystem variant="industry" />

    <section id="hidden-challenge" className="bg-white py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="The hidden growth challenge">Acquisition gets the first visit. Systems determine the years after it.</Heading><div className="mt-12 grid gap-8 lg:grid-cols-[.62fr_.38fr]"><Reveal className="space-y-6 text-xl leading-9 text-ink/65"><p>Paid social, influencer partnerships, redesigned websites, and promotions often work at the top of the wellness funnel. New people find the business and book an initial appointment or class.</p><p>The harder problem follows. A med spa client receives no treatment-window follow-up. A fitness trial quietly ends. A nutrition client gets a generic recap but no check-in. A recovery client misses the ideal second-appointment window.</p><p>The treatment, class, or consultation may have been excellent. What broke was the reminder, next step, or follow-up that depended on someone remembering during a busy day.</p></Reveal><Reveal delay={.08} className="flex min-h-[390px] flex-col justify-between rounded-[2rem] bg-flux p-8 text-white md:p-10"><p className="flux-kicker text-white/60">The real growth decision</p><p className="font-display text-4xl font-medium leading-tight">Will this person become a client for years or remain one transaction?</p><p className="text-sm leading-7 text-white/70">Most businesses rarely measure the systems deciding that outcome.</p></Reveal></div></div></section>

    <section className="bg-pulse-light py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="The relationship journey">Long-term growth develops across seven connected moments.</Heading><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{journey.map(([number, title, body], index) => <Reveal key={title} delay={index * .035} className="flex min-h-[280px] flex-col justify-between rounded-[2rem] bg-white p-8 transition-transform duration-500 hover:-translate-y-1"><span className="text-xs font-bold text-flux">{number}</span><div><h3 className="font-display text-3xl font-medium">{title}</h3><p className="mt-5 text-sm leading-7 text-ink/58">{body}</p></div></Reveal>)}</div><p className="mt-10 max-w-5xl text-xl leading-9 text-ink/65">Businesses that treat the entire journey as one connected system retain more of the clients they already worked to acquire.</p></div></section>

    <section className="bg-white py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="What it is">The connective layer beneath booking, communication, customer records, and follow-up.</Heading><div className="mt-12 grid gap-10 lg:grid-cols-[.58fr_.42fr]"><Reveal className="space-y-6 text-xl leading-9 text-ink/65"><p>Wellness Operating Intelligence connects how a business is discovered, how it understands customers, how it communicates and delivers experiences, and how automation and AI support the relationship.</p><p>It reveals clients approaching a natural rebooking window, early signs of lapsing, service and acquisition channels producing long-term value, and whether follow-up happens consistently.</p><p>Staff gain full context without asking returning clients to repeat their history, while managers see retention and rebooking rates alongside new-client volume.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-ink p-8 text-white md:p-10"><p className="flux-kicker text-flux">Connected customer context</p><ul className="mt-10 space-y-5 text-base leading-8 text-white/65"><li>Visible rebooking windows</li><li>Scheduled post-visit follow-up</li><li>History-based personalization</li><li>Retention and renewal visibility</li><li>Less repetitive administrative work</li></ul><Link href="/operating-intelligence" className="flux-button mt-10 bg-white text-ink">Explore Operating Intelligence <ArrowUpRight size={16} /></Link></Reveal></div></div></section>

    <section className="relative overflow-hidden bg-ink py-20 text-white md:py-28"><FluidShapes /><div className="flux-shell relative z-10"><Heading eyebrow="The Flux wellness framework" light>Five layers that grow the client base instead of cycling it.</Heading><div className="mt-14 grid border-t border-white/20">{framework.map(([number, title, body, href], index) => <Reveal key={title} delay={index * .04}><Link href={href} className="group grid gap-5 border-b border-white/20 py-8 transition-colors hover:bg-white hover:px-6 hover:text-ink md:grid-cols-[.1fr_.32fr_.5fr_.08fr] md:items-center"><span className="text-xs font-bold text-flux">{number}</span><h3 className="font-display text-2xl font-medium md:text-3xl">{title}</h3><p className="leading-8 opacity-60">{body}</p><ArrowUpRight className="ml-auto transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /></Link></Reveal>)}</div></div></section>

    <section className="bg-cream py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="Why marketing is not enough">Promotions create waves. Relationships create durable growth.</Heading><div className="mt-12 grid gap-5 lg:grid-cols-2"><Reveal className="rounded-[2rem] bg-white p-8 md:p-11"><p className="flux-kicker text-ink/40">Traditional wellness growth</p><p className="mt-10 font-display text-4xl font-medium">Campaign. Promotion. New bookings. Repeat when volume slows.</p><p className="mt-8 text-lg leading-9 text-ink/60">The model treats each booking as fresh acquisition and rarely asks what happened to last quarter&apos;s clients.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-flux p-8 text-white md:p-11"><p className="flux-kicker text-white/60">Connected wellness growth</p><p className="mt-10 font-display text-4xl font-medium">Experience. Follow-up. Rebooking. Renewal. Relationship.</p><p className="mt-8 text-lg leading-9 text-white/70">Better retention can outperform greater acquisition spend without structured follow-up behind it.</p></Reveal></div><p className="mt-10 max-w-5xl text-xl leading-9 text-ink/65">Track first-visit rebooking, return within expected cadence, membership renewal, and revenue from existing clients alongside first-time bookings.</p></div></section>

    <section className="relative overflow-hidden bg-pulse py-20 md:py-28"><FluidShapes /><div className="flux-shell relative z-10"><Heading eyebrow="AI and wellness businesses">Automate consistency while the human relationship continues to lead.</Heading><div className="mt-12 grid gap-10 lg:grid-cols-[.6fr_.4fr]"><Reveal className="space-y-6 text-xl leading-9 text-ink/65"><p>Wellness research increasingly begins with questions asked to AI assistants. Specific, structured service information helps systems understand and reference a business accurately.</p><p>AI can personalize recommendations using client history, automate reminders and rebooking prompts, answer common scheduling questions, and support customers during peak hours.</p><p>The strongest approach distinguishes where automation improves responsiveness from where the practitioner, instructor, or front-desk relationship must lead.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-ink p-8 text-white md:p-10"><p className="flux-kicker text-flux">The operating principle</p><p className="mt-10 font-display text-4xl font-medium leading-tight">Use intelligence to remember the relationship, not remove the people from it.</p><Link href="/ai-discovery" className="flux-button mt-10 bg-white text-ink">Explore AI Discovery <ArrowUpRight size={16} /></Link></Reveal></div></div></section>

    <section className="bg-white py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="Wellness businesses Flux supports">Different models. The same relationship and retention challenge.</Heading><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{businesses.map(([title, body], index) => <Reveal key={title} delay={index * .03} className="flex min-h-[240px] flex-col justify-between rounded-[1.75rem] border border-ink/10 p-7 transition-[color,background-color,border-color,box-shadow,opacity,transform] duration-500 hover:-translate-y-1 hover:border-flux/35"><span className="text-xs font-bold text-flux">0{index + 1}</span><div><h3 className="font-display text-2xl font-medium">{title}</h3><p className="mt-4 text-sm leading-7 text-ink/55">{body}</p></div></Reveal>)}</div></div></section>

    <section className="bg-ink py-20 text-white md:py-28"><div className="flux-shell"><Heading eyebrow="Built on Flux Operating Intelligence" light>The wellness application of a broader connected system.</Heading><div className="mt-12 grid gap-8 lg:grid-cols-[.58fr_.42fr]"><Reveal className="space-y-6 text-xl leading-9 text-white/60"><p>Wellness businesses are relationship-driven service businesses competing in a crowded, visually saturated market. Their system must connect discovery to experience, experience to follow-up, and follow-up to retention.</p><p>The same principles apply to a <Link className="text-white underline underline-offset-4" href="/industries/legal">legal practice</Link>, <Link className="text-white underline underline-offset-4" href="/industries/healthcare">healthcare business</Link>, or <Link className="text-white underline underline-offset-4" href="/industries/home-services">home services company</Link>, adapted to the way customers engage and return.</p></Reveal><div className="grid gap-3">{[["Revenue Intelligence", "/revenue-intelligence"], ["Customer Progression", "/customer-progression"], ["AI Discovery", "/ai-discovery"], ["Operating Intelligence", "/operating-intelligence"], ["Business Intelligence Audit", "/business-intelligence-audit"]].map(([title, href], index) => <Reveal key={href} delay={index * .04}><Link href={href} className="group flex items-center justify-between rounded-2xl border border-white/20 p-5 transition-colors hover:bg-white hover:text-ink"><span className="font-display text-xl font-medium">{title}</span><ArrowUpRight className="text-flux transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /></Link></Reveal>)}</div></div></div></section>

    <section className="bg-cream py-20 md:py-28"><div className="flux-shell"><Heading eyebrow="FAQ">Wellness operating intelligence, explained.</Heading><div className="mt-12 divide-y divide-ink/15 border-y border-ink/15">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-ink/15 transition-transform duration-500 group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>

    <section className="relative overflow-hidden bg-flux py-20 text-white md:py-28"><m.div animate={{ rotate: 360 }} transition={{ duration: 38, repeat: Infinity, ease: "linear" }} className="absolute -right-40 -top-40 h-[34rem] w-[34rem] rounded-[42%_58%_66%_34%] border border-white/25" /><div className="flux-shell relative z-10"><p className="flux-kicker text-white/65">Business Intelligence Audit</p><Reveal><h2 className="mt-7 max-w-6xl font-display text-[clamp(3rem,5.5vw,5.7rem)] font-medium leading-[.95] tracking-[-.06em]">Find where discovery, bookings, and long-term relationships are being lost.</h2></Reveal><p className="mt-8 max-w-3xl text-xl leading-9 text-white/70">Map your customer journey against the five layers of the Wellness Intelligence Framework.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/business-intelligence-audit" className="flux-button bg-white text-ink">Measure your intelligence score <ArrowUpRight size={16} /></Link><Link href="/contact" className="flux-button border border-white/35 text-white">Talk to Flux about your business</Link></div></div></section>
  </>;
}
