"use client";

import Link from "next/link";
import { motion, useScroll, useTransform } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Bot, Map, MessageCircle, Mic, Search, Sparkles } from "lucide-react";
import { useRef } from "react";

const channels = [
  ["Google", "Search results and AI Overviews that answer questions directly.", Search],
  ["ChatGPT", "Conversational recommendations that name businesses directly.", MessageCircle],
  ["Gemini", "AI discovery integrated into Google products and Android.", Sparkles],
  ["Perplexity", "Answer-led search grounded in cited sources.", Bot],
  ["Maps", "Local discovery increasingly summarized and interpreted by AI.", Map],
  ["Voice", "Spoken questions answered without a traditional results page.", Mic],
];
const components = [
  ["01", "Search Intelligence", "The traditional SEO foundation still matters: technical health, relevant content, and the language customers use. AI Discovery builds on it rather than replacing it."],
  ["02", "Entity Intelligence", "Machines must consistently understand who you are, what you do, where you operate, and whom you serve before they can recommend you confidently."],
  ["03", "Content Intelligence", "AI systems favor content that answers real questions directly and clearly—content they can quote, summarize, and rely on with confidence."],
  ["04", "Reputation Intelligence", "Reviews, mentions, and third-party references help systems judge trustworthiness and verify that a business is credible beyond its own website."],
  ["05", "Structured Intelligence", "Schema, organization data, and explicit relationships between services, locations, and business type provide an unambiguous source machines can understand."],
];
const faqs = [
  ["What is AI Discovery?", "AI Discovery is the practice of helping a business become visible and understandable across search engines, AI assistants, and recommendation systems, so it can be found regardless of which one a customer uses to look for it."],
  ["What is AI search optimization?", "AI search optimization is the work of making a business's information clear, consistent, and structured enough that AI systems like ChatGPT, Gemini, and Google's AI Overviews can confidently recommend it in response to a customer's question."],
  ["How is AI Discovery different from SEO?", "Traditional SEO focuses mainly on ranking in search engine results pages. AI Discovery builds on that foundation but extends it to how AI systems understand and recommend a business directly, including in conversations where no traditional results page ever appears."],
  ["How do businesses appear in ChatGPT results?", "By having a clear, consistent digital presence: accurate business information published in structured formats, content that directly answers common customer questions, and a credible reputation reflected in reviews and third-party mentions that AI systems can draw on with confidence."],
  ["Will SEO still matter in the AI era?", "Yes. Traditional SEO remains the foundation AI systems draw much of their understanding from. AI Discovery doesn't replace SEO, it extends it to cover the additional channels where customers are now asking for recommendations directly."],
];

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <motion.div initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .14 }} transition={{ delay, duration: .7, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</motion.div>;
}
function Heading({ eyebrow, children, light = false }: { eyebrow: string; children: React.ReactNode; light?: boolean }) {
  return <Reveal className={`border-t pt-5 ${light ? "border-white/20" : "border-ink/15"}`}><p className="flux-kicker text-flux">{eyebrow}</p><h2 className="mt-7 max-w-5xl font-display text-[clamp(2.6rem,4.7vw,4.8rem)] font-medium leading-[.98] tracking-[-.06em]">{children}</h2></Reveal>;
}
function DiscoveryOrb() {
  return <div className="relative min-h-[430px] overflow-hidden rounded-[2rem] bg-ink text-white">{[0, 1, 2].map((ring) => <motion.div key={ring} animate={{ rotate: ring % 2 ? -360 : 360, scale: [1, 1.04, 1] }} transition={{ rotate: { duration: 22 + ring * 8, repeat: Infinity, ease: "linear" }, scale: { duration: 5 + ring, repeat: Infinity } }} className="absolute left-1/2 top-1/2 rounded-[42%_58%_63%_37%] border border-white/15" style={{ width: `${170 + ring * 95}px`, height: `${170 + ring * 95}px`, marginLeft: `${-(170 + ring * 95) / 2}px`, marginTop: `${-(170 + ring * 95) / 2}px` }} />)}<motion.div animate={{ borderRadius: ["42% 58% 65% 35%", "61% 39% 44% 56%", "35% 65% 58% 42%", "42% 58% 65% 35%"] }} transition={{ duration: 8, repeat: Infinity }} className="absolute left-1/2 top-1/2 flex h-36 w-36 -translate-x-1/2 -translate-y-1/2 items-center justify-center bg-flux shadow-[0_0_80px_rgba(207,55,35,.4)]"><Sparkles size={34} /></motion.div>{["Search", "Answer", "Recommend"].map((label, index) => <motion.span key={label} animate={{ y: [0, -8, 0] }} transition={{ duration: 3.5 + index, repeat: Infinity }} className="absolute rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-semibold backdrop-blur" style={{ left: `${12 + index * 29}%`, top: `${20 + (index % 2) * 58}%` }}>{label}</motion.span>)}</div>;
}

export default function AIDiscoveryPage() {
  const componentRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: componentRef, offset: ["start end", "end start"] });
  const lineScale = useTransform(scrollYProgress, [.1, .82], [0, 1]);
  return <>
    <section className="relative overflow-hidden bg-cream pb-16 pt-28 md:pt-32"><motion.div animate={{ x: [0, 55, -25, 0], y: [0, -45, 35, 0], borderRadius: ["38% 62% 56% 44%", "65% 35% 43% 57%", "44% 56% 66% 34%", "38% 62% 56% 44%"] }} transition={{ duration: 19, repeat: Infinity, ease: "easeInOut" }} className="pointer-events-none absolute -right-32 top-20 h-[31rem] w-[31rem] bg-pulse opacity-40 blur-2xl" /><div className="flux-shell relative z-10"><nav aria-label="Breadcrumb" className="border-t border-ink/15 pt-5 text-xs text-ink/45"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/solutions">Solutions</Link><span className="mx-2">/</span><span>AI Discovery</span></nav><div className="grid gap-12 py-12 lg:grid-cols-[1.18fr_.82fr] lg:items-end lg:py-16"><motion.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .82 }}><p className="flux-kicker mb-7 text-flux">AI Discovery</p><h1 className="max-w-6xl font-display text-[clamp(3.35rem,6.15vw,6.4rem)] font-medium leading-[.91] tracking-[-.07em]">Getting found when search isn&apos;t just <span className="text-flux">Google anymore.</span></h1></motion.div><motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15, duration: .72 }} className="border-t border-ink/15 pt-6"><p className="text-lg leading-8 text-ink/65">Customers used to search, click, and land on your website. Now they ask ChatGPT, Gemini, or Google&apos;s AI Overview for a recommendation—and may never see a list of links.</p><p className="mt-5 text-lg leading-8 text-ink/65">AI Discovery helps your business become visible and recommendable across the entire way people find businesses now.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/business-intelligence-audit" className="flux-button flux-button-red">Get a free AI Visibility Assessment <ArrowUpRight size={16} /></Link><a href="#components" className="flux-button flux-button-line">See how AI Discovery works</a></div></motion.div></div><a href="#search-change" className="group ml-auto flex w-fit items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-ink/45">Explore the shift <span className="flex h-10 w-10 items-center justify-center rounded-full border border-ink/15 transition-all duration-500 group-hover:translate-y-1 group-hover:bg-ink group-hover:text-white"><ArrowDownRight size={16} /></span></a></div></section>

    <section id="search-change" className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Search is changing">There is no page two when an AI makes the recommendation directly.</Heading><div className="mt-14 grid gap-10 lg:grid-cols-[.56fr_.44fr]"><Reveal className="space-y-7 text-xl leading-9 text-ink/65"><p>For twenty years, being found online meant ranking in Google. That path still exists, but it is no longer the only one—and for a growing number of searches, it is not even the main one.</p><p>A customer might get a direct Google AI Overview, ask ChatGPT to recommend a clinic or contractor, or ask Gemini and Perplexity the same question and receive different answers built from different sources.</p><p>The system is not sending the customer to a page of links. It is making the recommendation. Your business either gets mentioned, or it does not exist in that conversation.</p><p>Traditional SEO still matters. But businesses optimizing only for the old path risk being ignored by a faster-growing discovery channel. AI Discovery is the work of showing up in both.</p></Reveal><DiscoveryOrb /></div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="What it is">Be visible and understood wherever customers ask for an answer.</Heading><div className="mt-14 grid gap-6 lg:grid-cols-2"><Reveal className="rounded-[2rem] bg-white p-8 md:p-12"><p className="text-xl leading-9 text-ink/68">AI Discovery helps a business become visible and understandable across search engines, AI assistants, and recommendation systems, regardless of which one a customer happens to use.</p><p className="mt-7 text-xl leading-9 text-ink/68">It matters to nearly every service business because customers who once scanned ten links increasingly ask one direct question and act on the answer.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-ink p-8 text-white md:p-12"><p className="text-xl leading-9 text-white/65">AI recommendations depend on how clearly identity, services, location, and reputation are represented across the web—and how consistently that information appears in sources the system trusts.</p><p className="mt-8 font-display text-3xl font-medium">The goal is not to game an algorithm. It is to make the machine&apos;s understanding accurate, complete, and consistent.</p></Reveal></div></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="From rankings to recommendations" light>Position is no longer the entire game. Understanding is.</Heading><div className="mt-14 grid gap-5 lg:grid-cols-2"><Reveal className="rounded-[2rem] border border-white/20 p-8 md:p-12"><p className="flux-kicker text-white/40">Old model</p><p className="mt-12 font-display text-5xl font-medium">Position #1.<br />Get the click.</p><p className="mt-10 text-base leading-8 text-white/55">Let the customer decide whether you are the right fit after reaching the site.</p></Reveal><Reveal delay={.08} className="rounded-[2rem] bg-flux p-8 md:p-12"><p className="flux-kicker text-white/60">New model</p><p className="mt-12 font-display text-5xl font-medium">Become the trusted answer.</p><p className="mt-10 text-base leading-8 text-white/70">Be named directly because the system has enough clear, consistent, credible information to recommend you confidently.</p></Reveal></div><p className="mt-12 max-w-4xl text-xl leading-9 text-white/60">One is a competition for position. The other asks whether your business is understood well enough to be recommended at all.</p></div></section>

    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="The AI Discovery layer">One connected visibility surface across six discovery environments.</Heading><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{channels.map(([title, body, Icon], index) => { const ChannelIcon = Icon; return <Reveal key={title as string} delay={index * .05} className={`group flex min-h-[280px] flex-col justify-between rounded-[1.75rem] p-7 transition-[transform,border-radius] duration-500 hover:-translate-y-2 hover:rounded-[2.2rem] ${index === 1 ? "bg-flux text-white" : index === 3 ? "bg-pulse-light" : "bg-cream"}`}><div className="flex items-start justify-between"><span className="text-xs font-bold opacity-45">0{index + 1}</span><ChannelIcon className="transition-transform duration-500 group-hover:scale-110" /></div><div><h3 className="font-display text-3xl font-medium">{title as string}</h3><p className="mt-5 text-sm leading-7 opacity-65">{body as string}</p></div></Reveal>; })}</div><p className="mt-10 max-w-4xl text-xl leading-9 text-ink/65">Visibility in one system does not guarantee visibility in another. Each draws from different sources and weighs them differently, so AI Discovery treats them as one connected surface.</p></div></section>

    <section id="components" ref={componentRef} className="relative overflow-hidden bg-cream py-24 md:py-36"><div className="pointer-events-none absolute -left-44 top-1/3 h-96 w-96 rounded-full bg-pulse/40 blur-3xl" /><div className="flux-shell relative z-10"><Heading eyebrow="The components">Five forms of intelligence that make a business understandable.</Heading><div className="relative mt-16"><div className="absolute bottom-0 left-[19px] top-0 w-px bg-ink/15 md:left-1/2" /><motion.div style={{ scaleY: lineScale, transformOrigin: "top" }} className="absolute bottom-0 left-[19px] top-0 w-px bg-flux md:left-1/2" />{components.map(([number, title, body], index) => <Reveal key={title} className="relative mb-8 grid gap-6 pl-14 md:grid-cols-2 md:pl-0"><span className="absolute left-0 top-8 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-flux text-xs font-bold text-white md:left-1/2 md:-translate-x-1/2">{number}</span><article className={`rounded-[2rem] border border-ink/10 bg-white p-8 shadow-[0_20px_70px_rgba(6,7,10,.06)] md:p-11 ${index % 2 ? "md:col-start-2 md:ml-12" : "md:mr-12"}`}><h3 className="font-display text-3xl font-medium md:text-4xl">{title}</h3><p className="mt-6 text-base leading-8 text-ink/60">{body}</p></article></Reveal>)}</div></div></section>

    <section className="bg-flux py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Powered by Operating Intelligence" light>Discovery creates attention. Connected systems turn attention into revenue.</Heading><div className="mt-14 grid gap-10 border-t border-white/25 pt-8 lg:grid-cols-[.62fr_.38fr]"><Reveal className="space-y-7 text-xl leading-9 text-white/70"><p>AI Discovery is the part of Flux&apos;s Operating Intelligence system responsible for helping customers find and choose a business before booking, communication, and follow-up begin.</p><p>The sequence matters: Operating Intelligence is the overall connected system; AI Discovery brings the customer in; then systems such as the Patient Revenue System ensure that interest becomes an appointment and revenue.</p><p>Discovery without capture wastes visibility. A conversion system without discovery has nobody arriving to convert.</p></Reveal><Link href="/operating-intelligence" className="group flex min-h-[240px] flex-col justify-between rounded-[2rem] bg-white p-8 text-ink transition-transform duration-500 hover:-translate-y-2"><ArrowUpRight className="ml-auto transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /><p className="font-display text-3xl font-medium">Explore Operating Intelligence</p></Link></div></div></section>

    <section className="bg-white py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Traditional SEO vs AI Discovery">SEO helped businesses rank. AI Discovery helps them become understood.</Heading><div className="mt-14 grid overflow-hidden rounded-[2rem] border border-ink/15 md:grid-cols-2"><Reveal className="p-8 md:p-12"><p className="flux-kicker text-ink/40">Traditional SEO</p><p className="mt-10 text-xl leading-9 text-ink/65">Focuses mainly on rankings: keywords, backlinks, and technical fixes aimed at getting a page onto page one of Google.</p></Reveal><Reveal delay={.08} className="bg-ink p-8 text-white md:p-12"><p className="flux-kicker text-flux">AI Discovery</p><p className="mt-10 text-xl leading-9 text-white/65">Extends that foundation so AI systems understand and recommend the business directly—even where no traditional results page appears.</p></Reveal></div></div></section>

    <section className="bg-pulse-light py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="Who this is built for">Businesses that depend on being found by people who do not know them yet.</Heading><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{[["Healthcare clinics", "/industries/healthcare"], ["Home services", "/industries/home-services"], ["Legal firms", "/industries/legal"], ["Wellness businesses", "/industries/wellness"], ["Professional services", "/solutions"]].map(([title, href], index) => <Reveal key={title} delay={index * .05}><Link href={href} className="group flex min-h-[230px] flex-col justify-between rounded-[1.75rem] bg-white p-7 transition-transform duration-500 hover:-translate-y-2"><span className="text-xs font-bold text-flux">0{index + 1}</span><div className="flex items-end justify-between gap-4"><h3 className="font-display text-2xl font-medium">{title}</h3><ArrowUpRight className="shrink-0 transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /></div></Link></Reveal>)}</div><p className="mt-10 max-w-4xl text-lg leading-8 text-ink/65">It is especially valuable for businesses already investing in SEO that suspect it is producing fewer qualified enquiries—or that see competitors recommended by ChatGPT and AI Overviews while they remain absent.</p></div></section>

    <section className="bg-ink py-24 text-white md:py-36"><div className="flux-shell"><Heading eyebrow="Related systems" light>Continue from discovery into conversion and intelligence.</Heading><div className="mt-14 grid border-t border-white/20 md:grid-cols-2 lg:grid-cols-5">{[["Patient Revenue System", "/patient-revenue-system"], ["Revenue Intelligence", "/revenue-intelligence"], ["Operating Intelligence", "/operating-intelligence"], ["Patient Revenue System for Clinics", "/clinics"], ["AI Search Insights", "/blog"]].map(([title, href]) => <Link key={title} href={href} className="group flex min-h-[240px] flex-col justify-between border-b border-white/20 p-7 transition-colors duration-500 hover:bg-white hover:text-ink md:border-r"><ArrowUpRight className="ml-auto transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" /><h3 className="font-display text-2xl font-medium">{title}</h3></Link>)}</div></div></section>

    <section className="bg-cream py-24 md:py-36"><div className="flux-shell"><Heading eyebrow="FAQ">Questions about AI search visibility.</Heading><div className="mt-14 divide-y divide-ink/15 border-y border-ink/15">{faqs.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-display text-xl font-medium md:text-2xl">{question}<span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-ink/15 transition-transform duration-500 group-open:rotate-45">+</span></summary><p className="max-w-4xl pt-5 text-base leading-8 text-ink/60">{answer}</p></details>)}</div></div></section>

    <section className="relative overflow-hidden bg-flux py-24 text-white md:py-36"><motion.div animate={{ rotate: 360 }} transition={{ duration: 36, repeat: Infinity, ease: "linear" }} className="absolute -right-44 -top-44 h-[36rem] w-[36rem] rounded-[42%_58%_64%_36%] border border-white/20" /><div className="flux-shell relative z-10"><p className="flux-kicker text-white/60">Free AI Visibility Assessment</p><Reveal><h2 className="mt-7 max-w-6xl font-display text-[clamp(3rem,5.5vw,5.7rem)] font-medium leading-[.95] tracking-[-.06em]">See how your business appears across Google and AI search.</h2></Reveal><p className="mt-9 max-w-3xl text-xl leading-9 text-white/70">We&apos;ll show you how your business currently appears—or does not—across Google, AI Overviews, ChatGPT, and Gemini, and what is needed to close the gap. No obligation; we respond within 24 hours.</p><Link href="/business-intelligence-audit" className="flux-button mt-10 bg-white text-ink">Get your free assessment <ArrowUpRight size={16} /></Link></div></section>
  </>;
}
